/*
	Copyright (c) 2004-2012, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
(function(b,k){var h,m,l=function(){},o=function(a){for(var c in a)return 0;return 1},f={}.toString,i=function(a){return"[object Function]"==f.call(a)},n=function(a){return"[object String]"==f.call(a)},a=function(a){return"[object Array]"==f.call(a)},d=function(a,c){if(a)for(var b=0;b<a.length;)c(a[b++])},c=function(a,c){for(var b in c)a[b]=c[b];return a},e=function(a,b){return c(Error(a),{src:"dojoLoader",info:b})},j=1,p=function(){return"_"+j++},g=function(a,c,b){return sa(a,c,b,0,g)},r=this,t=
r.document,u=t&&t.createElement("DiV"),s=g.has=function(a){return i(w[a])?w[a]=w[a](r,t,u):w[a]},w=s.cache=k.hasCache;s.add=function(a,c,b,d){(void 0===w[a]||d)&&(w[a]=c);return b&&s(a)};for(var q in b.has)s.add(q,b.has[q],0,1);g.async=1;var N=new Function("return eval(arguments[0]);");g.eval=function(a,c){return N(a+"\r\n////@ sourceURL="+c)};var E={},L=g.signal=function(c,b){var g=E[c];d(g&&g.slice(0),function(c){c.apply(null,a(b)?b:[b])})},H=g.on=function(a,c){var b=E[a]||(E[a]=[]);b.push(c);return{remove:function(){for(var a=
0;a<b.length;a++)if(b[a]===c){b.splice(a,1);break}}}},O=[],P={},X=[],T={},v=g.map={},x=[],A={},y="",B={},G={};q={};var U=function(a){var c,b,d,g;for(c in G)b=G[c],(d=c.match(/^url\:(.+)/))?B["url:"+ta(d[1],a)]=b:"*now"==c?g=b:"*noref"!=c&&(d=Y(c,a),B[d.mid]=B["url:"+d.url]=b);g&&g(ga(a));G={}},Q=function(a){return a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,function(a){return"\\"+a})},R=function(a,c){c.splice(0,c.length);for(var b in a)c.push([b,a[b],RegExp("^"+Q(b)+"(/|$)"),b.length]);c.sort(function(a,
c){return c[3]-a[3]});return c},I=function(a){var b=a.name;b||(b=a,a={name:b});a=c({main:"main"},a);a.location=a.location?a.location:b;if(a.packageMap)v[b]=a.packageMap;if(!a.main.indexOf("./"))a.main=a.main.substring(2);T[b]=a},C=[],K=function(a,b,e){for(var j in a){if("waitSeconds"==j)g.waitms=1E3*(a[j]||0);"cacheBust"==j&&(y=a[j]?n(a[j])?a[j]:(new Date).getTime()+"":"");if("baseUrl"==j||"combo"==j)g[j]=a[j];a[j]!==w&&(g.rawConfig[j]=a[j],"has"!=j&&s.add("config-"+j,a[j],0,b))}if(!g.baseUrl)g.baseUrl=
"./";/\/$/.test(g.baseUrl)||(g.baseUrl+="/");for(j in a.has)s.add(j,a.has[j],0,b);d(a.packages,I);for(m in a.packagePaths)d(a.packagePaths[m],function(a){var b=m+"/"+a;n(a)&&(a={name:a});a.location=b;I(a)});R(c(v,a.map),x);d(x,function(a){a[1]=R(a[1],[]);if("*"==a[0])x.star=a});R(c(P,a.paths),X);d(a.aliases,function(a){n(a[0])&&(a[0]=RegExp("^"+Q(a[0])+"$"));O.push(a)});if(b)C.push({config:a.config});else for(j in a.config)b=S(j,e),b.config=c(b.config||{},a.config[j]);if(a.cache)U(),G=a.cache,a.cache["*noref"]&&
U();L("config",[a,g.rawConfig])};if(s("dojo-cdn")){var z=t.getElementsByTagName("script");h=0;for(var D,F,Z,V;h<z.length;)if(D=z[h++],(Z=D.getAttribute("src"))&&(V=Z.match(/(((.*)\/)|^)dojo\.js(\W|$)/i))){F=V[3]||"";k.baseUrl=k.baseUrl||F;(Z=D.getAttribute("data-dojo-config")||D.getAttribute("djConfig"))&&(q=g.eval("({ "+Z+" })","data-dojo-config"));break}}g.rawConfig={};K(k,1);if(s("dojo-cdn"))(T.dojo.location=F)&&(F+="/"),T.dijit.location=F+"../dijit/",T.dojox.location=F+"../dojox/";K(b,1);K(q,
1);var $=function(a){ha(function(){d(a.deps,ua)})},sa=function(b,d,j,r,i){var o;if(n(b)){if((o=S(b,r,!0))&&o.executed)return o.result;throw e("undefinedModule",b);}a(b)||(K(b,0,r),b=d,d=j);if(a(b))if(b.length){for(var j="require*"+p(),f,u=[],h=0;h<b.length;)f=b[h++],u.push(S(f,r));o=c(aa("",j,0,""),{injected:2,deps:u,def:d||l,require:r?r.require:g,gc:1});A[o.mid]=o;$(o);var s=W&&0!="sync";ha(function(){ia(o,s)});o.executed||M.push(o);ba()}else d&&d();return i},ga=function(a){if(!a)return g;var b=
a.require;if(!b)b=function(c,d,g){return sa(c,d,g,a,b)},a.require=c(b,g),b.module=a,b.toUrl=function(b){return ta(b,a)},b.toAbsMid=function(b){return ja(b,a)};return b},M=[],ca=[],J={},Ea=function(a){a.injected=1;J[a.mid]=1;a.url&&(J[a.url]=a.pack||1);Da()},da=function(a){a.injected=2;delete J[a.mid];a.url&&delete J[a.url];o(J)&&Fa()},Ga=g.idle=function(){return!ca.length&&o(J)&&!M.length&&!W},ka=function(a,b){if(b)for(var c=0;c<b.length;c++)if(b[c][2].test(a))return b[c];return 0},va=function(a){for(var b=
[],c,d,a=a.replace(/\\/g,"/").split("/");a.length;)c=a.shift(),".."==c&&b.length&&".."!=d?(b.pop(),d=b[b.length-1]):"."!=c&&b.push(d=c);return b.join("/")},aa=function(a,b,c,d){return{pid:a,mid:b,pack:c,url:d,executed:0,def:0}},wa=function(a,b,c,g,j,p,n,r){var o,f,u,h;h=/^\./.test(a);if(/(^\/)|(\:)|(\.js$)/.test(a)||h&&!b)return aa(0,a,0,a);a=va(h?b.mid+"/../"+a:a);if(/^\./.test(a))throw e("irrationalPath",a);b&&(u=ka(b.mid,p));(u=(u=u||p.star)&&ka(a,u[1]))&&(a=u[1]+a.substring(u[3]));b=(V=a.match(/^([^\/]+)(\/(.+))?$/))?
V[1]:"";(o=c[b])?a=b+"/"+(f=V[3]||o.main):b="";var l=0;d(O,function(b){var c=a.match(b[0]);c&&0<c.length&&(l=i(b[1])?a.replace(b[0],b[1]):b[1])});if(l)return wa(l,0,c,g,j,p,n,r);if(c=g[a])return r?aa(c.pid,c.mid,c.pack,c.url):g[a];g=(u=ka(a,n))?u[1]+a.substring(u[3]):b?o.location+"/"+f:a;/(^\/)|(\:)/.test(g)||(g=j+g);return aa(b,a,o,va(g+".js"))},Y=function(a,b){return wa(a,b,T,A,g.baseUrl,x,X)},xa=function(a,b,c){return a.normalize?a.normalize(b,function(a){return ja(a,c)}):ja(b,c)},ya=0,S=function(a,
b,c){var d,g;(d=a.match(/^(.+?)\!(.*)$/))?(g=S(d[1],b,c),5===g.executed&&!g.load&&la(g),g.load?(d=xa(g,d[2],b),a=g.mid+"!"+(g.dynamic?++ya+"!":"")+d):(d=d[2],a=g.mid+"!"+ ++ya+"!waitingForPlugin"),a={plugin:g,mid:a,req:ga(b),prid:d}):a=Y(a,b);return A[a.mid]||!c&&(A[a.mid]=a)},ja=g.toAbsMid=function(a,b){return Y(a,b).mid},ta=g.toUrl=function(a,b){var c=Y(a+"/x",b),d=c.url;return za(0===c.pid?a:d.substring(0,d.length-5))},Aa={injected:2,executed:5,def:3,result:3};F=function(a){return A[a]=c({mid:a},
Aa)};var Ha=F("require"),Ia=F("exports"),Ja=F("module"),ea={},ma=0,la=function(a){var b=a.result;a.dynamic=b.dynamic;a.normalize=b.normalize;a.load=b.load;return a},Ka=function(a){var b={};d(a.loadQ,function(d){var g=xa(a,d.prid,d.req.module),e=a.dynamic?d.mid.replace(/waitingForPlugin$/,g):a.mid+"!"+g,g=c(c({},d),{mid:e,prid:g,injected:0});A[e]||Ba(A[e]=g);b[d.mid]=A[e];da(d);delete A[d.mid]});a.loadQ=0;var g=function(a){for(var c=a.deps||[],d=0;d<c.length;d++)(a=b[c[d].mid])&&(c[d]=a)},e;for(e in A)g(A[e]);
d(M,g)},na=function(a){g.trace("loader-finish-exec",[a.mid]);a.executed=5;a.defOrder=ma++;a.loadQ&&(la(a),Ka(a));for(h=0;h<M.length;)M[h]===a?M.splice(h,1):h++;/^require\*/.test(a.mid)&&delete A[a.mid]},La=[],ia=function(a,b){if(4===a.executed)return g.trace("loader-circular-dependency",[La.concat(a.mid).join("->")]),!a.def||b?ea:a.cjs&&a.cjs.exports;if(!a.executed){if(!a.def)return ea;var c=a.mid,d=a.deps||[],e,j=[],p=0;for(a.executed=4;p<d.length;){e=d[p++];e=e===Ha?ga(a):e===Ia?a.cjs.exports:e===
Ja?a.cjs:ia(e,b);if(e===ea)return a.executed=0,g.trace("loader-exec-module",["abort",c]),ea;j.push(e)}g.trace("loader-run-factory",[a.mid]);c=a.def;j=i(c)?c.apply(null,j):c;a.result=void 0===j&&a.cjs?a.cjs.exports:j;na(a)}return a.result},W=0,ha=function(a){try{W++,a()}finally{W--}Ga()&&L("idle",[])},ba=function(){W||ha(function(){for(var a,b,c=0;c<M.length;)a=ma,b=M[c],ia(b),a!=ma?c=0:c++})};void 0===s("dojo-loader-eval-hint-url")&&s.add("dojo-loader-eval-hint-url",1);var za=function(a){a+="";return a+
(y?(/\?/.test(a)?"&":"?")+y:"")},Ba=function(a){var b=a.plugin;5===b.executed&&!b.load&&la(b);var c=function(b){a.result=b;da(a);na(a);ba()};b.load?b.load(a.prid,a.req,c):b.loadQ?b.loadQ.push(a):(b.loadQ=[a],M.unshift(b),ua(b))},fa=0,oa=0,pa=0,Ma=function(a,b){s("config-stripStrict")&&(a=a.replace(/"use strict"/g,""));pa=1;a===fa?fa.call(null):g.eval(a,s("dojo-loader-eval-hint-url")?b.url:b.mid);pa=0},ua=function(a){var b=a.mid,d=a.url;if(!a.executed&&!a.injected&&!(J[b]||a.url&&(a.pack&&J[a.url]===
a.pack||1==J[a.url])))if(Ea(a),a.plugin)Ba(a);else{var e=function(){Na(a);2!==a.injected&&(da(a),c(a,Aa),g.trace("loader-define-nonmodule",[a.url]));ba()};(fa=B[b]||B["url:"+a.url])?(g.trace("loader-inject",["cache",a.mid,d]),Ma(fa,a),e()):(g.trace("loader-inject",["script",a.mid,d]),oa=a,g.injectUrl(za(d),e,a),oa=0)}},qa=function(a,b,d){g.trace("loader-define-module",[a.mid,b]);if(2===a.injected)return L("error",e("multipleDefine",a)),a;c(a,{deps:b,def:d,cjs:{id:a.mid,uri:a.url,exports:a.result=
{},setExports:function(b){a.cjs.exports=b},config:function(){return a.config}}});for(var j=0;j<b.length;j++)b[j]=S(b[j],a);da(a);if(!i(d)&&!b.length)a.result=d,na(a);return a},Na=function(a,b){for(var c=[],g,e;ca.length;)e=ca.shift(),b&&(e[0]=b.shift()),g=e[0]&&S(e[0])||a,c.push([g,e[1],e[2]]);U(a);d(c,function(a){$(qa.apply(null,a))})},Fa=l,Da=l;s.add("ie-event-behavior",!!t.attachEvent&&("undefined"===typeof opera||"[object Opera]"!=opera.toString()));var ra=function(a,b,c,d){if(s("ie-event-behavior"))return a.attachEvent(c,
d),function(){a.detachEvent(c,d)};a.addEventListener(b,d,!1);return function(){a.removeEventListener(b,d,!1)}},Oa=ra(window,"load","onload",function(){g.pageLoaded=1;"complete"!=t.readyState&&(t.readyState="complete");Oa()}),Ca=t.getElementsByTagName("script")[0],Pa=Ca.parentNode;g.injectUrl=function(a,b,c){var c=c.node=t.createElement("script"),d=ra(c,"load","onreadystatechange",function(a){var a=a||window.event,c=a.target||a.srcElement;if("load"===a.type||/complete|loaded/.test(c.readyState))d(),
g(),b&&b()}),g=ra(c,"error","onerror",function(b){d();g();L("error",e("scriptError",[a,b]))});c.type="text/javascript";c.charset="utf-8";c.src=a;Pa.insertBefore(c,Ca);return c};g.log=l;g.trace=l;F=function(a,b,c){var d=arguments.length,j=["require","exports","module"],p=[0,a,b];1==d?p=[0,i(a)?j:[],a]:2==d&&n(a)?p=[a,i(b)?j:[],b]:3==d&&(p=[a,b,c]);g.trace("loader-define",p.slice(0,2));if((d=p[0]&&S(p[0]))&&!J[d.mid])$(qa(d,p[1],p[2]));else if(!s("ie-event-behavior")||pa)ca.push(p);else{d=d||oa;if(!d)for(a in J)if((j=
A[a])&&j.node&&"interactive"===j.node.readyState){d=j;break}d?(U(d),$(qa(d,p[1],p[2]))):L("error",e("ieDefineFailed",p[0]));ba()}};F.amd={vendor:"dojotoolkit.org"};c(c(g,k.loaderPatch),b.loaderPatch);H("error",function(a){try{if(console.error(a),a instanceof Error)for(var b in a);}catch(c){}});c(g,{uid:p,cache:B,packs:T});if(!r.define)r.define=F,r.require=g,d(C,function(a){K(a)}),H=q.deps||b.deps||k.deps,q=q.callback||b.callback||k.callback,g.boot=H||q?[H||[],q]:0})(this.dojoConfig||this.djConfig||
this.require||{},{async:1,hasCache:{"config-selectorEngine":"lite","config-tlmSiblingOfDojo":1,"dojo-built":1,"dojo-loader":1,dom:1,"host-browser":1},packages:[{location:"../dojox",name:"dojox"},{location:"../dijit",name:"dijit"},{location:"../app",name:"app"},{location:".",name:"dojo"}]});
require({cache:{"dojo/_base/fx":function(){define("./kernel,./config,./lang,../Evented,./Color,./connect,./sniff,../dom,../dom-style".split(","),function(b,k,h,m,l,o,f,i,n){var a=h.mixin,d={},c=d._Line=function(a,b){this.start=a;this.end=b};c.prototype.getValue=function(a){return(this.end-this.start)*a+this.start};var e=d.Animation=function(b){a(this,b);if(h.isArray(this.curve))this.curve=new c(this.curve[0],this.curve[1])};e.prototype=new m;h.extend(e,{duration:350,repeat:0,rate:20,_percent:0,_startRepeatCount:0,
_getStep:function(){var a=this._percent,b=this.easing;return b?b(a):a},_fire:function(a,b){var c=b||[];if(this[a])if(k.debugAtAllCosts)this[a].apply(this,c);else try{this[a].apply(this,c)}catch(d){console.error("exception in animation handler for:",a),console.error(d)}return this},play:function(a,b){this._delayTimer&&this._clearTimer();if(b)this._stopTimer(),this._active=this._paused=!1,this._percent=0;else if(this._active&&!this._paused)return this;this._fire("beforeBegin",[this.node]);var c=a||
this.delay,d=h.hitch(this,"_play",b);if(0<c)return this._delayTimer=setTimeout(d,c),this;d();return this},_play:function(){this._delayTimer&&this._clearTimer();this._startTime=(new Date).valueOf();this._paused&&(this._startTime-=this.duration*this._percent);this._active=!0;this._paused=!1;var a=this.curve.getValue(this._getStep());if(!this._percent){if(!this._startRepeatCount)this._startRepeatCount=this.repeat;this._fire("onBegin",[a])}this._fire("onPlay",[a]);this._cycle();return this},pause:function(){this._delayTimer&&
this._clearTimer();this._stopTimer();if(!this._active)return this;this._paused=!0;this._fire("onPause",[this.curve.getValue(this._getStep())]);return this},gotoPercent:function(a,b){this._stopTimer();this._active=this._paused=!0;this._percent=a;b&&this.play();return this},stop:function(a){this._delayTimer&&this._clearTimer();if(!this._timer)return this;this._stopTimer();if(a)this._percent=1;this._fire("onStop",[this.curve.getValue(this._getStep())]);this._active=this._paused=!1;return this},status:function(){return this._active?
this._paused?"paused":"playing":"stopped"},_cycle:function(){if(this._active){var a=(new Date).valueOf(),a=0===this.duration?1:(a-this._startTime)/this.duration;1<=a&&(a=1);this._percent=a;this.easing&&(a=this.easing(a));this._fire("onAnimate",[this.curve.getValue(a)]);if(1>this._percent)this._startTimer();else{this._active=!1;if(0<this.repeat)this.repeat--,this.play(null,!0);else if(-1==this.repeat)this.play(null,!0);else if(this._startRepeatCount)this.repeat=this._startRepeatCount,this._startRepeatCount=
0;this._percent=0;this._fire("onEnd",[this.node]);!this.repeat&&this._stopTimer()}}return this},_clearTimer:function(){clearTimeout(this._delayTimer);delete this._delayTimer}});var j=0,p=null,g={run:function(){}};h.extend(e,{_startTimer:function(){if(!this._timer)this._timer=o.connect(g,"run",this,"_cycle"),j++;p||(p=setInterval(h.hitch(g,"run"),this.rate))},_stopTimer:function(){if(this._timer)o.disconnect(this._timer),this._timer=null,j--;0>=j&&(clearInterval(p),p=null,j=0)}});var r=f("ie")?function(a){var b=
a.style;if(!b.width.length&&"auto"==n.get(a,"width"))b.width="auto"}:function(){};d._fade=function(b){b.node=i.byId(b.node);var c=a({properties:{}},b),b=c.properties.opacity={};b.start=!("start"in c)?function(){return+n.get(c.node,"opacity")||0}:c.start;b.end=c.end;b=d.animateProperty(c);o.connect(b,"beforeBegin",h.partial(r,c.node));return b};d.fadeIn=function(b){return d._fade(a({end:1},b))};d.fadeOut=function(b){return d._fade(a({end:0},b))};d._defaultEasing=function(a){return 0.5+Math.sin((a+
1.5)*Math.PI)/2};var t=function(a){this._properties=a;for(var b in a){var c=a[b];if(c.start instanceof l)c.tempColor=new l}};t.prototype.getValue=function(a){var b={},c;for(c in this._properties){var d=this._properties[c],g=d.start;g instanceof l?b[c]=l.blendColors(g,d.end,a,d.tempColor).toCss():h.isArray(g)||(b[c]=(d.end-g)*a+g+("opacity"!=c?d.units||"px":0))}return b};d.animateProperty=function(c){var d=c.node=i.byId(c.node);if(!c.easing)c.easing=b._defaultEasing;c=new e(c);o.connect(c,"beforeBegin",
c,function(){var b={},c;for(c in this.properties){if("width"==c||"height"==c)this.node.display="block";var g=this.properties[c];h.isFunction(g)&&(g=g(d));g=b[c]=a({},h.isObject(g)?g:{end:g});if(h.isFunction(g.start))g.start=g.start(d);if(h.isFunction(g.end))g.end=g.end(d);var e=0<=c.toLowerCase().indexOf("color"),j=function(a,b){var c={height:a.offsetHeight,width:a.offsetWidth}[b];if(void 0!==c)return c;c=n.get(a,b);return"opacity"==b?+c:e?c:parseFloat(c)};if("end"in g){if(!("start"in g))g.start=
j(d,c)}else g.end=j(d,c);e?(g.start=new l(g.start),g.end=new l(g.end)):g.start="opacity"==c?+g.start:parseFloat(g.start)}this.curve=new t(b)});o.connect(c,"onAnimate",h.hitch(n,"set",c.node));return c};d.anim=function(a,b,c,g,j,p){return d.animateProperty({node:a,duration:c||e.prototype.duration,properties:b,easing:g,onEnd:j}).play(p||0)};a(b,d);b._Animation=e;return d})},"dojo/dom-form":function(){define(["./_base/lang","./dom","./io-query","./json"],function(b,k,h,m){var l={fieldToObject:function(b){var f=
null;if(b=k.byId(b)){var i=b.name,n=(b.type||"").toLowerCase();if(i&&n&&!b.disabled)if("radio"==n||"checkbox"==n){if(b.checked)f=b.value}else if(b.multiple){f=[];for(b=[b.firstChild];b.length;)for(i=b.pop();i;i=i.nextSibling)if(1==i.nodeType&&"option"==i.tagName.toLowerCase())i.selected&&f.push(i.value);else{i.nextSibling&&b.push(i.nextSibling);i.firstChild&&b.push(i.firstChild);break}}else f=b.value}return f},toObject:function(o){for(var f={},o=k.byId(o).elements,i=0,n=o.length;i<n;++i){var a=o[i],
d=a.name,c=(a.type||"").toLowerCase();if(d&&c&&0>"file|submit|image|reset|button".indexOf(c)&&!a.disabled){var e=f,j=d,a=l.fieldToObject(a);if(null!==a){var p=e[j];"string"==typeof p?e[j]=[p,a]:b.isArray(p)?p.push(a):e[j]=a}if("image"==c)f[d+".x"]=f[d+".y"]=f[d].x=f[d].y=0}}return f},toQuery:function(b){return h.objectToQuery(l.toObject(b))},toJson:function(b,f){return m.stringify(l.toObject(b),null,f?4:0)}};return l})},"dojo/errors/RequestError":function(){define(["./create"],function(b){return b("RequestError",
function(b,h){this.response=h})})},"dojo/_base/html":function(){define("dojo/_base/html","./kernel,../dom,../dom-style,../dom-attr,../dom-prop,../dom-class,../dom-construct,../dom-geometry".split(","),function(b,k,h,m,l,o,f,i){b.byId=k.byId;b.isDescendant=k.isDescendant;b.setSelectable=k.setSelectable;b.getAttr=m.get;b.setAttr=m.set;b.hasAttr=m.has;b.removeAttr=m.remove;b.getNodeProp=m.getNodeProp;b.attr=function(b,a,d){return 2==arguments.length?m["string"==typeof a?"get":"set"](b,a):m.set(b,a,d)};
b.hasClass=o.contains;b.addClass=o.add;b.removeClass=o.remove;b.toggleClass=o.toggle;b.replaceClass=o.replace;b._toDom=b.toDom=f.toDom;b.place=f.place;b.create=f.create;b.empty=function(b){f.empty(b)};b._destroyElement=b.destroy=function(b){f.destroy(b)};b._getPadExtents=b.getPadExtents=i.getPadExtents;b._getBorderExtents=b.getBorderExtents=i.getBorderExtents;b._getPadBorderExtents=b.getPadBorderExtents=i.getPadBorderExtents;b._getMarginExtents=b.getMarginExtents=i.getMarginExtents;b._getMarginSize=
b.getMarginSize=i.getMarginSize;b._getMarginBox=b.getMarginBox=i.getMarginBox;b.setMarginBox=i.setMarginBox;b._getContentBox=b.getContentBox=i.getContentBox;b.setContentSize=i.setContentSize;b._isBodyLtr=b.isBodyLtr=i.isBodyLtr;b._docScroll=b.docScroll=i.docScroll;b._getIeDocumentElementOffset=b.getIeDocumentElementOffset=i.getIeDocumentElementOffset;b._fixIeBiDiScrollLeft=b.fixIeBiDiScrollLeft=i.fixIeBiDiScrollLeft;b.position=i.position;b.marginBox=function(b,a){return a?i.setMarginBox(b,a):i.getMarginBox(b)};
b.contentBox=function(b,a){return a?i.setContentSize(b,a):i.getContentBox(b)};b.coords=function(n,a){b.deprecated("dojo.coords()","Use dojo.position() or dojo.marginBox().");var n=k.byId(n),d=h.getComputedStyle(n),d=i.getMarginBox(n,d),c=i.position(n,a);d.x=c.x;d.y=c.y;return d};b.getProp=l.get;b.setProp=l.set;b.prop=function(b,a,d){return 2==arguments.length?l["string"==typeof a?"get":"set"](b,a):l.set(b,a,d)};b.getStyle=h.get;b.setStyle=h.set;b.getComputedStyle=h.getComputedStyle;b.__toPixelValue=
b.toPixelValue=h.toPixelValue;b.style=function(b,a,d){switch(arguments.length){case 1:return h.get(b);case 2:return h["string"==typeof a?"get":"set"](b,a)}return h.set(b,a,d)};return b})},"dojo/_base/kernel":function(){define(["../has","./config","require","module"],function(b,k,h,m){var l,b={},o={},f={config:k,global:this,dijit:b,dojox:o},b={dojo:["dojo",f],dijit:["dijit",b],dojox:["dojox",o]},m=h.map&&h.map[m.id.match(/[^\/]+/)[0]];for(l in m)b[l]?b[l][0]=m[l]:b[l]=[m[l],{}];for(l in b)m=b[l],m[1]._scopeName=
m[0],k.noGlobals||(this[m[0]]=m[1]);f.scopeMap=b;f.baseUrl=f.config.baseUrl=h.baseUrl;f.isAsync=h.async;f.locale=k.locale;k="$Rev: 30226 $".match(/\d+/);f.version={major:1,minor:8,patch:3,flag:"",revision:k?+k[0]:NaN,toString:function(){var b=f.version;return b.major+"."+b.minor+"."+b.patch+b.flag+" ("+b.revision+")"}};Function("d","d.eval = function(){return d.global.eval ? d.global.eval(arguments[0]) : eval(arguments[0]);}")(f);f.exit=function(){};"undefined"!=typeof console||(console={});for(var h=
"assert,count,debug,dir,dirxml,error,group,groupEnd,info,profile,profileEnd,time,timeEnd,trace,warn,log".split(","),i,k=0;i=h[k++];)console[i]||function(){var b=i+"";console[b]="log"in console?function(){var a=Array.apply({},arguments);a.unshift(b+":");console.log(a.join(" "))}:function(){};console[b]._fake=!0}();f.deprecated=f.experimental=function(){};f._hasResource={};return f})},"dojo/io-query":function(){define(["./_base/lang"],function(b){var k={};return{objectToQuery:function(h){var m=encodeURIComponent,
l=[],o;for(o in h){var f=h[o];if(f!=k[o]){var i=m(o)+"=";if(b.isArray(f))for(var n=0,a=f.length;n<a;++n)l.push(i+m(f[n]));else l.push(i+m(f))}}return l.join("&")},queryToObject:function(h){for(var m=decodeURIComponent,h=h.split("&"),l={},o,f,i=0,n=h.length;i<n;++i)if(f=h[i],f.length){var a=f.indexOf("=");0>a?(o=m(f),f=""):(o=m(f.slice(0,a)),f=m(f.slice(a+1)));"string"==typeof l[o]&&(l[o]=[l[o]]);b.isArray(l[o])?l[o].push(f):l[o]=f}return l}}})},"dojo/_base/Deferred":function(){define("./kernel,../Deferred,../promise/Promise,../errors/CancelError,../has,./lang,../when".split(","),
function(b,k,h,m,l,o,f){var i=function(){},n=Object.freeze||function(){},a=b.Deferred=function(b){function c(a){if(p)throw Error("This deferred has already been resolved");j=a;p=!0;e()}function e(){for(var a;!a&&f;){var b=f;f=f.next;if(a=b.progress==i)p=!1;var c=g?b.error:b.resolved;l("config-useDeferredInstrumentation")&&g&&k.instrumentRejected&&k.instrumentRejected(j,!!c);if(c)try{var d=c(j);d&&"function"===typeof d.then?d.then(o.hitch(b.deferred,"resolve"),o.hitch(b.deferred,"reject"),o.hitch(b.deferred,
"progress")):(c=a&&void 0===d,a&&!c&&(g=d instanceof Error),b.deferred[c&&g?"reject":"resolve"](c?j:d))}catch(e){b.deferred.reject(e)}else g?b.deferred.reject(j):b.deferred.resolve(j)}}var j,p,g,r,f,u=this.promise=new h;this.resolve=this.callback=function(a){this.fired=0;this.results=[a,null];c(a)};this.reject=this.errback=function(a){g=!0;this.fired=1;l("config-useDeferredInstrumentation")&&k.instrumentRejected&&k.instrumentRejected(a,!!f);c(a);this.results=[null,a]};this.progress=function(a){for(var b=
f;b;){var c=b.progress;c&&c(a);b=b.next}};this.addCallbacks=function(a,b){this.then(a,b,i);return this};u.then=this.then=function(b,c,d){var g=d==i?this:new a(u.cancel),b={resolved:b,error:c,progress:d,deferred:g};f?r=r.next=b:f=r=b;p&&e();return g.promise};var s=this;u.cancel=this.cancel=function(){if(!p){var a=b&&b(s);if(!p)a instanceof Error||(a=new m(a)),a.log=!1,s.reject(a)}};n(u)};o.extend(a,{addCallback:function(a){return this.addCallbacks(o.hitch.apply(b,arguments))},addErrback:function(a){return this.addCallbacks(null,
o.hitch.apply(b,arguments))},addBoth:function(a){var c=o.hitch.apply(b,arguments);return this.addCallbacks(c,c)},fired:-1});a.when=b.when=f;return a})},"dojo/NodeList-dom":function(){define("./_base/kernel,./query,./_base/array,./_base/lang,./dom-class,./dom-construct,./dom-geometry,./dom-attr,./dom-style".split(","),function(b,k,h,m,l,o,f,i,n){function a(a){return function(b,c,d){return 2==arguments.length?a["string"==typeof c?"get":"set"](b,c):a.set(b,c,d)}}var d=function(a){return 1==a.length&&
"string"==typeof a[0]},c=function(a){var b=a.parentNode;b&&b.removeChild(a)},e=k.NodeList,j=e._adaptWithCondition,p=e._adaptAsForEach,g=e._adaptAsMap;m.extend(e,{_normalize:function(a,c){var d=!0===a.parse;if("string"==typeof a.template)var g=a.templateFunc||b.string&&b.string.substitute,a=g?g(a.template,a):a;g=typeof a;"string"==g||"number"==g?(a=o.toDom(a,c&&c.ownerDocument),a=11==a.nodeType?m._toArray(a.childNodes):[a]):m.isArrayLike(a)?m.isArray(a)||(a=m._toArray(a)):a=[a];if(d)a._runParse=!0;
return a},_cloneNode:function(a){return a.cloneNode(!0)},_place:function(a,c,d,g){if(!(1!=c.nodeType&&"only"==d))for(var e,j=a.length,p=j-1;0<=p;p--){var f=g?this._cloneNode(a[p]):a[p];if(a._runParse&&b.parser&&b.parser.parse){e||(e=c.ownerDocument.createElement("div"));e.appendChild(f);b.parser.parse(e);for(f=e.firstChild;e.firstChild;)e.removeChild(e.firstChild)}p==j-1?o.place(f,c,d):c.parentNode.insertBefore(f,c);c=f}},position:g(f.position),attr:j(a(i),d),style:j(a(n),d),addClass:p(l.add),removeClass:p(l.remove),
toggleClass:p(l.toggle),replaceClass:p(l.replace),empty:p(o.empty),removeAttr:p(i.remove),marginBox:g(f.getMarginBox),place:function(a,b){var c=k(a)[0];return this.forEach(function(a){o.place(a,c,b)})},orphan:function(a){return(a?k._filterResult(this,a):this).forEach(c)},adopt:function(a,b){return k(a).place(this[0],b)._stash(this)},query:function(a){if(!a)return this;var b=new e;this.map(function(c){k(a,c).forEach(function(a){void 0!==a&&b.push(a)})});return b._stash(this)},filter:function(a){var b=
arguments,c=this,d=0;if("string"==typeof a){c=k._filterResult(this,b[0]);if(1==b.length)return c._stash(this);d=1}return this._wrap(h.filter(c,b[d],b[d+1]),this)},addContent:function(a,b){for(var a=this._normalize(a,this[0]),c=0,d;d=this[c];c++)this._place(a,d,b,0<c);return this}});return e})},"dojo/query":function(){define("./_base/kernel,./has,./dom,./on,./_base/array,./_base/lang,./selector/_loader,./selector/_loader!default".split(","),function(b,k,h,m,l,o,f,i){function n(a,b){var c=function(c,
d){if("string"==typeof d&&(d=h.byId(d),!d))return new b([]);var g="string"==typeof c?a(c,d):c?c.orphan?c:[c]:[];return g.orphan?g:new b(g)};c.matches=a.match||function(a,b,d){return 0<c.filter([a],b,d).length};c.filter=a.filter||function(a,b,d){return c(b,d).filter(function(b){return-1<l.indexOf(a,b)})};if("function"!=typeof a)var d=a.search,a=function(a,b){return d(b||document,a)};return c}k.add("array-extensible",function(){return 1==o.delegate([],{length:1}).length&&!k("bug-for-in-skips-shadowed")});
var a=Array.prototype,d=a.slice,c=a.concat,e=l.forEach,j=function(a,c,g){c=[0].concat(d.call(c,0));g=g||b.global;return function(b){c[0]=b;return a.apply(g,c)}},p=function(a){var b=this instanceof g&&k("array-extensible");"number"==typeof a&&(a=Array(a));var c=a&&"length"in a?a:arguments;if(b||!c.sort){for(var d=b?this:[],e=d.length=c.length,j=0;j<e;j++)d[j]=c[j];if(b)return d;c=d}o._mixin(c,r);c._NodeListCtor=function(a){return g(a)};return c},g=p,r=g.prototype=k("array-extensible")?[]:{};g._wrap=
r._wrap=function(a,b,c){a=new (c||this._NodeListCtor||g)(a);return b?a._stash(b):a};g._adaptAsMap=function(a,b){return function(){return this.map(j(a,arguments,b))}};g._adaptAsForEach=function(a,b){return function(){this.forEach(j(a,arguments,b));return this}};g._adaptAsFilter=function(a,b){return function(){return this.filter(j(a,arguments,b))}};g._adaptWithCondition=function(a,c,d){return function(){var g=arguments,e=j(a,g,d);if(c.call(d||b.global,g))return this.map(e);this.forEach(e);return this}};
e(["slice","splice"],function(b){var c=a[b];r[b]=function(){return this._wrap(c.apply(this,arguments),"slice"==b?this:null)}});e(["indexOf","lastIndexOf","every","some"],function(a){var c=l[a];r[a]=function(){return c.apply(b,[this].concat(d.call(arguments,0)))}});o.extend(p,{constructor:g,_NodeListCtor:g,toString:function(){return this.join(",")},_stash:function(a){this._parent=a;return this},on:function(a,b){var c=this.map(function(c){return m(c,a,b)});c.remove=function(){for(var a=0;a<c.length;a++)c[a].remove()};
return c},end:function(){return this._parent?this._parent:new this._NodeListCtor(0)},concat:function(a){var b=d.call(this,0),g=l.map(arguments,function(a){return d.call(a,0)});return this._wrap(c.apply(b,g),this)},map:function(a,b){return this._wrap(l.map(this,a,b),this)},forEach:function(a,b){e(this,a,b);return this},filter:function(a){var b=arguments,c=this,d=0;if("string"==typeof a){c=t._filterResult(this,b[0]);if(1==b.length)return c._stash(this);d=1}return this._wrap(l.filter(c,b[d],b[d+1]),
this)},instantiate:function(a,b){var c=o.isFunction(a)?a:o.getObject(a),b=b||{};return this.forEach(function(a){new c(b,a)})},at:function(){var a=new this._NodeListCtor(0);e(arguments,function(b){0>b&&(b=this.length+b);this[b]&&a.push(this[b])},this);return a._stash(this)}});var t=n(i,p);b.query=n(i,function(a){return p(a)});t.load=function(a,b,c){f.load(a,b,function(a){c(n(a,p))})};b._filterQueryResult=t._filterResult=function(a,b,c){return new p(t.filter(a,b,c))};b.NodeList=t.NodeList=p;return t})},
"dojo/has":function(){define(["require","module"],function(b){var k=b.has||function(){};k.add("dom-addeventlistener",!!document.addEventListener);k.add("touch","ontouchstart"in document);k.add("device-width",screen.availWidth||innerWidth);b=document.createElement("form");k.add("dom-attributes-explicit",0==b.attributes.length);k.add("dom-attributes-specified-flag",0<b.attributes.length&&40>b.attributes.length);k.clearElement=function(b){b.innerHTML="";return b};k.normalize=function(b,m){var l=b.match(/[\?:]|[^:\?]*/g),
o=0,f=function(b){var n=l[o++];if(":"==n)return 0;if("?"==l[o++]){if(!b&&k(n))return f();f(!0);return f(b)}return n||0};return(b=f())&&m(b)};k.load=function(b,m,l){b?m([b],l):l()};return k})},"dojo/json":function(){define(["./has"],function(b){var k="undefined"!=typeof JSON;b.add("json-parse",k);b.add("json-stringify",k&&'{"a":1}'==JSON.stringify({a:0},function(b,l){return l||1}));if(b("json-stringify"))return JSON;var h=function(b){return('"'+b.replace(/(["\\])/g,"\\$1")+'"').replace(/[\f]/g,"\\f").replace(/[\b]/g,
"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")};return{parse:b("json-parse")?JSON.parse:function(b,l){if(l&&!/^([\s\[\{]*(?:"(?:\\.|[^"])+"|-?\d[\d\.]*(?:[Ee][+-]?\d+)?|null|true|false|)[\s\]\}]*(?:,|:|$))+$/.test(b))throw new SyntaxError("Invalid characters in JSON");return eval("("+b+")")},stringify:function(b,l,o){function f(b,a,d){l&&(b=l(d,b));var c;c=typeof b;if("number"==c)return isFinite(b)?b+"":"null";if("boolean"==c)return b+"";if(null===b)return"null";if("string"==
typeof b)return h(b);if("function"==c||"undefined"==c)return i;if("function"==typeof b.toJSON)return f(b.toJSON(d),a,d);if(b instanceof Date)return'"{FullYear}-{Month+}-{Date}T{Hours}:{Minutes}:{Seconds}Z"'.replace(/\{(\w+)(\+)?\}/g,function(a,c,d){a=b["getUTC"+c]()+(d?1:0);return 10>a?"0"+a:a});if(b.valueOf()!==b)return f(b.valueOf(),a,d);var e=o?a+o:"",j=o?" ":"",p=o?"\n":"";if(b instanceof Array){for(var j=b.length,g=[],d=0;d<j;d++)c=f(b[d],e,d),"string"!=typeof c&&(c="null"),g.push(p+e+c);return"["+
g.join(",")+p+a+"]"}g=[];for(d in b){var r;if(b.hasOwnProperty(d)){if("number"==typeof d)r='"'+d+'"';else if("string"==typeof d)r=h(d);else continue;c=f(b[d],e,d);"string"==typeof c&&g.push(p+e+r+":"+j+c)}}return"{"+g.join(",")+p+a+"}"}var i;"string"==typeof l&&(o=l,l=null);return f(b,"","")}}})},"dojo/_base/declare":function(){define(["./kernel","../has","./lang"],function(b,k,h){function m(a,b){throw Error("declare"+(b?" "+b:"")+": "+a);}function l(a,b,c){var d,g,e,j,p,f,i,o=this._inherited=this._inherited||
{};"string"==typeof a&&(d=a,a=b,b=c);c=0;j=a.callee;(d=d||j.nom)||m("can't deduce a name to call inherited()",this.declaredClass);p=this.constructor._meta;e=p.bases;i=o.p;if(d!=E){if(o.c!==j&&(i=0,f=e[0],p=f._meta,p.hidden[d]!==j)){(g=p.chains)&&"string"==typeof g[d]&&m("calling chained method with inherited: "+d,this.declaredClass);do if(p=f._meta,g=f.prototype,p&&(g[d]===j&&g.hasOwnProperty(d)||p.hidden[d]===j))break;while(f=e[++i]);i=f?i:-1}if(f=e[++i])if(g=f.prototype,f._meta&&g.hasOwnProperty(d))c=
g[d];else{j=s[d];do if(g=f.prototype,(c=g[d])&&(f._meta?g.hasOwnProperty(d):c!==j))break;while(f=e[++i])}c=f&&c||s[d]}else{if(o.c!==j&&(i=0,(p=e[0]._meta)&&p.ctor!==j)){g=p.chains;for((!g||"manual"!==g.constructor)&&m("calling chained constructor with inherited",this.declaredClass);(f=e[++i])&&!((p=f._meta)&&p.ctor===j););i=f?i:-1}for(;(f=e[++i])&&!(c=(p=f._meta)?p.ctor:f););c=f&&c}o.c=c;o.p=i;if(c)return!0===b?c:c.apply(this,b||a)}function o(a,b){return"string"==typeof a?this.__inherited(a,b,!0):
this.__inherited(a,!0)}function f(a,b,c){var d=this.getInherited(a,b);if(d)return d.apply(this,c||b||a)}function i(a){for(var b=this.constructor._meta.bases,c=0,d=b.length;c<d;++c)if(b[c]===a)return!0;return this instanceof a}function n(a,b){for(var c in b)c!=E&&b.hasOwnProperty(c)&&(a[c]=b[c]);if(k("bug-for-in-skips-shadowed"))for(var d=h._extraNames,g=d.length;g;)c=d[--g],c!=E&&b.hasOwnProperty(c)&&(a[c]=b[c])}function a(a){t.safeMixin(this.prototype,a);return this}function d(a){return t([this].concat(a))}
function c(a,b){return function(){var v;var c=arguments,d=c,g=c[0],e,j;j=a.length;var p;if(!(this instanceof c.callee))return r(c);if(b&&(g&&g.preamble||this.preamble)){p=Array(a.length);p[0]=c;for(e=0;;){if(g=c[0])(g=g.preamble)&&(c=g.apply(this,c)||c);g=a[e].prototype;(g=g.hasOwnProperty("preamble")&&g.preamble)&&(c=g.apply(this,c)||c);if(++e==j)break;p[e]=c}}for(e=j-1;0<=e;--e)g=a[e],(v=(j=g._meta)?j.ctor:g,g=v)&&g.apply(this,p?p[e]:c);(g=this.postscript)&&g.apply(this,d)}}function e(a,b){return function(){var c=
arguments,d=c,g=c[0];if(!(this instanceof c.callee))return r(c);if(b){if(g)(g=g.preamble)&&(d=g.apply(this,d)||d);(g=this.preamble)&&g.apply(this,d)}a&&a.apply(this,c);(g=this.postscript)&&g.apply(this,c)}}function j(a){return function(){var v;var b=arguments,c=0,d,g;if(!(this instanceof b.callee))return r(b);for(;d=a[c];++c)if(v=(g=d._meta)?g.ctor:d,d=v){d.apply(this,b);break}(d=this.postscript)&&d.apply(this,b)}}function p(a,b,c){return function(){var d,g,e=0,j=1;c&&(e=b.length-1,j=-1);for(;d=b[e];e+=
j)g=d._meta,(d=(g?g.hidden:d.prototype)[a])&&d.apply(this,arguments)}}function g(a){q.prototype=a.prototype;a=new q;q.prototype=null;return a}function r(a){var b=a.callee,c=g(b);b.apply(c,a);return c}function t(b,f,r){"string"!=typeof b&&(r=f,f=b,b="");var r=r||{},k,q,v,x,A,y,B,G=1,U=f;if("[object Array]"==w.call(f)){G=b;v=[];x=[{cls:0,refs:[]}];y={};for(var Q=1,R=f.length,I=0,C,K,z,D;I<R;++I){(C=f[I])?"[object Function]"!=w.call(C)&&m("mixin #"+I+" is not a callable constructor.",G):m("mixin #"+
I+" is unknown. Did you use dojo.require to pull it in?",G);K=C._meta?C._meta.bases:[C];z=0;for(C=K.length-1;0<=C;--C){D=K[C].prototype;if(!D.hasOwnProperty("declaredClass"))D.declaredClass="uniqName_"+N++;D=D.declaredClass;y.hasOwnProperty(D)||(y[D]={count:0,refs:[],cls:K[C]},++Q);D=y[D];z&&z!==D&&(D.refs.push(z),++z.count);z=D}++z.count;x[0].refs.push(z)}for(;x.length;){z=x.pop();v.push(z.cls);for(--Q;q=z.refs,1==q.length;){z=q[0];if(!z||--z.count){z=0;break}v.push(z.cls);--Q}if(z)for(I=0,R=q.length;I<
R;++I)z=q[I],--z.count||x.push(z)}Q&&m("can't build consistent linearization",G);C=f[0];v[0]=C?C._meta&&C===v[v.length-C._meta.bases.length]?C._meta.bases.length:1:0;y=v;v=y[0];G=y.length-v;f=y[G]}else y=[0],f?"[object Function]"==w.call(f)?(v=f._meta,y=y.concat(v?v.bases:f)):m("base class is not a callable constructor.",b):null!==f&&m("unknown base class. Did you use dojo.require to pull it in?",b);if(f)for(q=G-1;;--q){k=g(f);if(!q)break;v=y[q];(v._meta?n:u)(k,v.prototype);x=new Function;x.superclass=
f;x.prototype=k;f=k.constructor=x}else k={};t.safeMixin(k,r);v=r.constructor;if(v!==s.constructor)v.nom=E,k.constructor=v;for(q=G-1;q;--q)(v=y[q]._meta)&&v.chains&&(B=u(B||{},v.chains));k["-chains-"]&&(B=u(B||{},k["-chains-"]));v=!B||!B.hasOwnProperty(E);y[0]=x=B&&"manual"===B.constructor?j(y):1==y.length?e(r.constructor,v):c(y,v);x._meta={bases:y,hidden:r,chains:B,parents:U,ctor:r.constructor};x.superclass=f&&f.prototype;x.extend=a;x.createSubclass=d;x.prototype=k;k.constructor=x;k.getInherited=
o;k.isInstanceOf=i;k.inherited=L;k.__inherited=l;if(b)k.declaredClass=b,h.setObject(b,x);if(B)for(A in B)if(k[A]&&"string"==typeof B[A]&&A!=E)v=k[A]=p(A,y,"after"===B[A]),v.nom=A;return x}var u=h.mixin,s=Object.prototype,w=s.toString,q=new Function,N=0,E="constructor",L=b.config.isDebug?f:l;b.safeMixin=t.safeMixin=function(a,b){var c,d;for(c in b)if(d=b[c],(d!==s[c]||!(c in s))&&c!=E){if("[object Function]"==w.call(d))d.nom=c;a[c]=d}if(k("bug-for-in-skips-shadowed"))for(var g=h._extraNames,e=g.length;e;)if(c=
g[--e],d=b[c],(d!==s[c]||!(c in s))&&c!=E){if("[object Function]"==w.call(d))d.nom=c;a[c]=d}return a};return b.declare=t})},"dojo/dom":function(){define(["./sniff","./_base/window"],function(b,k){if(7>=b("ie"))try{document.execCommand("BackgroundImageCache",!1,!0)}catch(h){}var m={};m.byId=b("ie")?function(b,f){if("string"!=typeof b)return b;var i=f||k.doc,n=b&&i.getElementById(b);if(n&&(n.attributes.id.value==b||n.id==b))return n;i=i.all[b];if(!i||i.nodeName)i=[i];for(var a=0;n=i[a++];)if(n.attributes&&
n.attributes.id&&n.attributes.id.value==b||n.id==b)return n}:function(b,f){return("string"==typeof b?(f||k.doc).getElementById(b):b)||null};m.isDescendant=function(b,f){try{b=m.byId(b);for(f=m.byId(f);b;){if(b==f)return!0;b=b.parentNode}}catch(i){}return!1};b.add("css-user-select",function(b,f,i){if(!i)return!1;var b=i.style,f=["Khtml","O","ms","Moz","Webkit"],i=f.length,n="userSelect";do if("undefined"!==typeof b[n])return n;while(i--&&(n=f[i]+"UserSelect"));return!1});var l=b("css-user-select");
m.setSelectable=l?function(b,f){m.byId(b).style[l]=f?"":"none"}:function(b,f){var b=m.byId(b),i=b.getElementsByTagName("*"),n=i.length;if(f)for(b.removeAttribute("unselectable");n--;)i[n].removeAttribute("unselectable");else for(b.setAttribute("unselectable","on");n--;)i[n].setAttribute("unselectable","on")};return m})},"dojo/_base/browser":function(){require.has&&require.has.add("config-selectorEngine","acme");define("../ready,./kernel,./connect,./unload,./window,./event,./html,./NodeList,../query,./xhr,./fx".split(","),
function(b){return b})},"dojo/errors/RequestTimeoutError":function(){define("dojo/errors/RequestTimeoutError",["./create","./RequestError"],function(b,k){return b("RequestTimeoutError",null,k,{dojoType:"timeout"})})},"dojo/dom-style":function(){define("dojo/dom-style",["./sniff","./dom"],function(b,k){function h(c,e,g){e=e.toLowerCase();if(b("ie")){if("auto"==g){if("height"==e)return c.offsetHeight;if("width"==e)return c.offsetWidth}if("fontweight"==e)switch(g){case 700:return"bold";default:return"normal"}}e in
a||(a[e]=d.test(e));return a[e]?o(c,g):g}var m,l={};m=b("webkit")?function(a){var b;if(1==a.nodeType){var c=a.ownerDocument.defaultView;b=c.getComputedStyle(a,null);if(!b&&a.style)a.style.display="",b=c.getComputedStyle(a,null)}return b||{}}:b("ie")&&(9>b("ie")||b("quirks"))?function(a){return 1==a.nodeType&&a.currentStyle?a.currentStyle:{}}:function(a){return 1==a.nodeType?a.ownerDocument.defaultView.getComputedStyle(a,null):{}};l.getComputedStyle=m;var o;o=b("ie")?function(a,b){if(!b)return 0;if("medium"==
b)return 4;if(b.slice&&"px"==b.slice(-2))return parseFloat(b);var c=a.style,d=a.runtimeStyle,e=c.left,f=d.left;d.left=a.currentStyle.left;try{c.left=b,b=c.pixelLeft}catch(i){b=0}c.left=e;d.left=f;return b}:function(a,b){return parseFloat(b)||0};l.toPixelValue=o;var f=function(a,b){try{return a.filters.item("DXImageTransform.Microsoft.Alpha")}catch(c){return b?{}:null}},i=9>b("ie")||10>b("ie")&&b("quirks")?function(a){try{return f(a).Opacity/100}catch(b){return 1}}:function(a){return m(a).opacity},
n=9>b("ie")||10>b("ie")&&b("quirks")?function(a,b){var c=100*b,d=1==b;a.style.zoom=d?"":1;if(f(a))f(a,1).Opacity=c;else{if(d)return b;a.style.filter+=" progid:DXImageTransform.Microsoft.Alpha(Opacity="+c+")"}f(a,1).Enabled=!d;if("tr"==a.tagName.toLowerCase())for(c=a.firstChild;c;c=c.nextSibling)"td"==c.tagName.toLowerCase()&&n(c,b);return b}:function(a,b){return a.style.opacity=b},a={left:!0,top:!0},d=/margin|padding|width|height|max|min|offset/,c=b("ie")?"styleFloat":"cssFloat",e={cssFloat:c,styleFloat:c,
"float":c};l.get=function(a,b){var c=k.byId(a),d=arguments.length;if(2==d&&"opacity"==b)return i(c);var b=e[b]||b,f=l.getComputedStyle(c);return 1==d?f:h(c,b,f[b]||c.style[b])};l.set=function(a,b,c){var d=k.byId(a),f=arguments.length,i="opacity"==b,b=e[b]||b;if(3==f)return i?n(d,c):d.style[b]=c;for(var h in b)l.set(a,h,b[h]);return l.getComputedStyle(d)};return l})},"dojo/dom-geometry":function(){define(["./sniff","./_base/window","./dom","./dom-style"],function(b,k,h,m){function l(a,b,c,e,j,f){f=
f||"px";a=a.style;if(!isNaN(b))a.left=b+f;if(!isNaN(c))a.top=c+f;if(0<=e)a.width=e+f;if(0<=j)a.height=j+f}function o(a){return"button"==a.tagName.toLowerCase()||"input"==a.tagName.toLowerCase()&&"button"==(a.getAttribute("type")||"").toLowerCase()}function f(a){return"border-box"==i.boxModel||"table"==a.tagName.toLowerCase()||o(a)}var i={boxModel:"content-box"};if(b("ie"))i.boxModel="BackCompat"==document.compatMode?"border-box":"content-box";i.getPadExtents=function(a,b){var a=h.byId(a),c=b||m.getComputedStyle(a),
e=m.toPixelValue,j=e(a,c.paddingLeft),f=e(a,c.paddingTop),g=e(a,c.paddingRight),c=e(a,c.paddingBottom);return{l:j,t:f,r:g,b:c,w:j+g,h:f+c}};i.getBorderExtents=function(a,b){var a=h.byId(a),c=m.toPixelValue,e=b||m.getComputedStyle(a),j="none"!=e.borderLeftStyle?c(a,e.borderLeftWidth):0,f="none"!=e.borderTopStyle?c(a,e.borderTopWidth):0,g="none"!=e.borderRightStyle?c(a,e.borderRightWidth):0,c="none"!=e.borderBottomStyle?c(a,e.borderBottomWidth):0;return{l:j,t:f,r:g,b:c,w:j+g,h:f+c}};i.getPadBorderExtents=
function(a,b){var a=h.byId(a),c=b||m.getComputedStyle(a),e=i.getPadExtents(a,c),c=i.getBorderExtents(a,c);return{l:e.l+c.l,t:e.t+c.t,r:e.r+c.r,b:e.b+c.b,w:e.w+c.w,h:e.h+c.h}};i.getMarginExtents=function(a,b){var a=h.byId(a),c=b||m.getComputedStyle(a),e=m.toPixelValue,j=e(a,c.marginLeft),f=e(a,c.marginTop),g=e(a,c.marginRight),c=e(a,c.marginBottom);return{l:j,t:f,r:g,b:c,w:j+g,h:f+c}};i.getMarginBox=function(a,d){var a=h.byId(a),c=d||m.getComputedStyle(a),e=i.getMarginExtents(a,c),j=a.offsetLeft-e.l,
f=a.offsetTop-e.t,g=a.parentNode,n=m.toPixelValue;if(b("mozilla")){var l=parseFloat(c.left),c=parseFloat(c.top);!isNaN(l)&&!isNaN(c)?(j=l,f=c):g&&g.style&&(g=m.getComputedStyle(g),"visible"!=g.overflow&&(j+="none"!=g.borderLeftStyle?n(a,g.borderLeftWidth):0,f+="none"!=g.borderTopStyle?n(a,g.borderTopWidth):0))}else if((b("opera")||8==b("ie")&&!b("quirks"))&&g)g=m.getComputedStyle(g),j-="none"!=g.borderLeftStyle?n(a,g.borderLeftWidth):0,f-="none"!=g.borderTopStyle?n(a,g.borderTopWidth):0;return{l:j,
t:f,w:a.offsetWidth+e.w,h:a.offsetHeight+e.h}};i.getContentBox=function(a,d){var a=h.byId(a),c=d||m.getComputedStyle(a),e=a.clientWidth,j=i.getPadExtents(a,c),f=i.getBorderExtents(a,c);e?(c=a.clientHeight,f.w=f.h=0):(e=a.offsetWidth,c=a.offsetHeight);b("opera")&&(j.l+=f.l,j.t+=f.t);return{l:j.l,t:j.t,w:e-j.w-f.w,h:c-j.h-f.h}};i.setContentSize=function(a,b,c){var a=h.byId(a),e=b.w,b=b.h;f(a)&&(c=i.getPadBorderExtents(a,c),0<=e&&(e+=c.w),0<=b&&(b+=c.h));l(a,NaN,NaN,e,b)};var n={l:0,t:0,w:0,h:0};i.setMarginBox=
function(a,d,c){var a=h.byId(a),e=c||m.getComputedStyle(a),c=d.w,j=d.h,p=f(a)?n:i.getPadBorderExtents(a,e),e=i.getMarginExtents(a,e);if(b("webkit")&&o(a)){var g=a.style;if(0<=c&&!g.width)g.width="4px";if(0<=j&&!g.height)g.height="4px"}0<=c&&(c=Math.max(c-p.w-e.w,0));0<=j&&(j=Math.max(j-p.h-e.h,0));l(a,d.l,d.t,c,j)};i.isBodyLtr=function(a){a=a||k.doc;return"ltr"==(k.body(a).dir||a.documentElement.dir||"ltr").toLowerCase()};i.docScroll=function(a){var a=a||k.doc,d=k.doc.parentWindow||k.doc.defaultView;
return"pageXOffset"in d?{x:d.pageXOffset,y:d.pageYOffset}:(d=b("quirks")?k.body(a):a.documentElement)&&{x:i.fixIeBiDiScrollLeft(d.scrollLeft||0,a),y:d.scrollTop||0}};if(b("ie"))i.getIeDocumentElementOffset=function(a){a=a||k.doc;a=a.documentElement;if(8>b("ie")){var d=a.getBoundingClientRect(),c=d.left,d=d.top;7>b("ie")&&(c+=a.clientLeft,d+=a.clientTop);return{x:0>c?0:c,y:0>d?0:d}}return{x:0,y:0}};i.fixIeBiDiScrollLeft=function(a,d){var d=d||k.doc,c=b("ie");if(c&&!i.isBodyLtr(d)){var e=b("quirks"),
f=e?k.body(d):d.documentElement,p=k.global;6==c&&!e&&p.frameElement&&f.scrollHeight>f.clientHeight&&(a+=f.clientLeft);return 8>c||e?a+f.clientWidth-f.scrollWidth:-a}return a};i.position=function(a,d){var a=h.byId(a),c=k.body(a.ownerDocument),e=a.getBoundingClientRect(),e={x:e.left,y:e.top,w:e.right-e.left,h:e.bottom-e.top};if(9>b("ie")){var f=i.getIeDocumentElementOffset(a.ownerDocument);e.x-=f.x+(b("quirks")?c.clientLeft+c.offsetLeft:0);e.y-=f.y+(b("quirks")?c.clientTop+c.offsetTop:0)}d&&(c=i.docScroll(a.ownerDocument),
e.x+=c.x,e.y+=c.y);return e};i.getMarginSize=function(a,b){var a=h.byId(a),c=i.getMarginExtents(a,b||m.getComputedStyle(a)),e=a.getBoundingClientRect();return{w:e.right-e.left+c.w,h:e.bottom-e.top+c.h}};i.normalizeEvent=function(a){if(!("layerX"in a))a.layerX=a.offsetX,a.layerY=a.offsetY;if(!b("dom-addeventlistener")){var d=a.target,d=d&&d.ownerDocument||document,c=b("quirks")?d.body:d.documentElement,e=i.getIeDocumentElementOffset(d);a.pageX=a.clientX+i.fixIeBiDiScrollLeft(c.scrollLeft||0,d)-e.x;
a.pageY=a.clientY+(c.scrollTop||0)-e.y}};return i})},"dojo/dom-prop":function(){define("exports,./_base/kernel,./sniff,./_base/lang,./dom,./dom-style,./dom-construct,./_base/connect".split(","),function(b,k,h,m,l,o,f,i){var n={},a=0,d=k._scopeName+"attrid";b.names={"class":"className","for":"htmlFor",tabindex:"tabIndex",readonly:"readOnly",colspan:"colSpan",frameborder:"frameBorder",rowspan:"rowSpan",valuetype:"valueType"};b.get=function(a,d){var a=l.byId(a),f=d.toLowerCase();return a[b.names[f]||
d]};b.set=function(c,e,j){c=l.byId(c);if(2==arguments.length&&"string"!=typeof e){for(var p in e)b.set(c,p,e[p]);return c}p=e.toLowerCase();p=b.names[p]||e;if("style"==p&&"string"!=typeof j)return o.set(c,j),c;if("innerHTML"==p)return h("ie")&&c.tagName.toLowerCase()in{col:1,colgroup:1,table:1,tbody:1,tfoot:1,thead:1,tr:1,title:1}?(f.empty(c),c.appendChild(f.toDom(j,c.ownerDocument))):c[p]=j,c;if(m.isFunction(j)){var g=c[d];g||(g=a++,c[d]=g);n[g]||(n[g]={});var k=n[g][p];if(k)i.disconnect(k);else try{delete c[p]}catch(t){}j?
n[g][p]=i.connect(c,p,j):c[p]=null;return c}c[p]=j;return c}})},"dojo/when":function(){define(["./Deferred","./promise/Promise"],function(b,k){return function(h,m,l,o){var f=h&&"function"===typeof h.then,i=f&&h instanceof k;if(f){if(!i)f=new b(h.cancel),h.then(f.resolve,f.reject,f.progress),h=f.promise}else return m?m(h):(new b).resolve(h);return m||l||o?h.then(m,l,o):h}})},"dojo/dom-attr":function(){define("exports,./sniff,./_base/lang,./dom,./dom-style,./dom-prop".split(","),function(b,k,h,m,l,
o){function f(a,b){var c=a.getAttributeNode&&a.getAttributeNode(b);return c&&c.specified}var i={innerHTML:1,className:1,htmlFor:k("ie"),value:1},n={classname:"class",htmlfor:"for",tabindex:"tabIndex",readonly:"readOnly"};b.has=function(a,b){var c=b.toLowerCase();return i[o.names[c]||b]||f(m.byId(a),n[c]||b)};b.get=function(a,b){var a=m.byId(a),c=b.toLowerCase(),e=o.names[c]||b,j=a[e];if(i[e]&&"undefined"!=typeof j||"href"!=e&&("boolean"==typeof j||h.isFunction(j)))return j;c=n[c]||b;return f(a,c)?
a.getAttribute(c):null};b.set=function(a,d,c){a=m.byId(a);if(2==arguments.length){for(var e in d)b.set(a,e,d[e]);return a}e=d.toLowerCase();var f=o.names[e]||d,p=i[f];if("style"==f&&"string"!=typeof c)return l.set(a,c),a;if(p||"boolean"==typeof c||h.isFunction(c))return o.set(a,d,c);a.setAttribute(n[e]||d,c);return a};b.remove=function(a,b){m.byId(a).removeAttribute(n[b.toLowerCase()]||b)};b.getNodeProp=function(a,b){var a=m.byId(a),c=b.toLowerCase(),e=o.names[c]||b;if(e in a&&"href"!=e)return a[e];
c=n[c]||b;return f(a,c)?a.getAttribute(c):null}})},"dojo/dom-construct":function(){define("exports,./_base/kernel,./sniff,./_base/window,./dom,./dom-attr,./on".split(","),function(b,k,h,m,l,o){function f(a,b){var c=b.parentNode;c&&c.insertBefore(a,b)}var i={option:["select"],tbody:["table"],thead:["table"],tfoot:["table"],tr:["table","tbody"],td:["table","tbody","tr"],th:["table","thead","tr"],legend:["fieldset"],caption:["table"],colgroup:["table"],col:["table","colgroup"],li:["ul"]},n=/<\s*([\w\:]+)/,
a={},d=0,c="__"+k._scopeName+"ToDomId",e;for(e in i)if(i.hasOwnProperty(e))k=i[e],k.pre="option"==e?'<select multiple="multiple">':"<"+k.join("><")+">",k.post="</"+k.reverse().join("></")+">";b.toDom=function(b,g){var g=g||m.doc,e=g[c];e||(g[c]=e=++d+"",a[e]=g.createElement("div"));var b=b+"",f=b.match(n),j=f?f[1].toLowerCase():"",e=a[e];if(f&&i[j]){f=i[j];e.innerHTML=f.pre+b+f.post;for(f=f.length;f;--f)e=e.firstChild}else e.innerHTML=b;if(1==e.childNodes.length)return e.removeChild(e.firstChild);
for(j=g.createDocumentFragment();f=e.firstChild;)j.appendChild(f);return j};b.place=function(a,c,d){c=l.byId(c);"string"==typeof a&&(a=/^\s*</.test(a)?b.toDom(a,c.ownerDocument):l.byId(a));if("number"==typeof d){var e=c.childNodes;!e.length||e.length<=d?c.appendChild(a):f(a,e[0>d?0:d])}else switch(d){case "before":f(a,c);break;case "after":d=a;(e=c.parentNode)&&(e.lastChild==c?e.appendChild(d):e.insertBefore(d,c.nextSibling));break;case "replace":c.parentNode.replaceChild(a,c);break;case "only":b.empty(c);
c.appendChild(a);break;case "first":if(c.firstChild){f(a,c.firstChild);break}default:c.appendChild(a)}return a};b.create=function(a,c,d,e){var f=m.doc;if(d)d=l.byId(d),f=d.ownerDocument;"string"==typeof a&&(a=f.createElement(a));c&&o.set(a,c);d&&b.place(a,d,e);return a};var j=h("ie")?function(a){try{a.innerHTML=""}catch(b){for(var c;c=a.lastChild;){var d=a;c.firstChild&&j(c);d&&d.removeChild(c)}}}:function(a){a.innerHTML=""};b.empty=function(a){j(l.byId(a))};b.destroy=function(a){if(a=l.byId(a)){var b=
a,a=a.parentNode;b.firstChild&&j(b);a&&a.removeChild(b)}}})},"dojo/request/xhr":function(){define("dojo/request/xhr",["../errors/RequestError","./watch","./handlers","./util","../has"],function(b,k,h,m,l){function o(a,c){var d=a.xhr;a.status=a.xhr.status;a.text=d.responseText;if("xml"===a.options.handleAs)a.data=d.responseXML;if(!c)try{h(a)}catch(e){c=e}c?this.reject(c):m.checkStatus(d.status)?this.resolve(a):(c=new b("Unable to load "+a.url+" status: "+d.status,a),this.reject(c))}function f(g,j,
h){var p=m.parseArgs(g,m.deepCreate(e,j),l("native-formdata")&&j&&j.data&&j.data instanceof FormData),g=p.url,j=p.options,s,w=m.deferred(p,d,i,n,o,function(){s&&s()}),q=p.xhr=f._create();if(!q)return w.cancel(new b("XHR was not created")),h?w:w.promise;p.getHeader=function(a){return this.xhr.getResponseHeader(a)};a&&(s=a(q,w,p));var N=j.data,E=!j.sync,L=j.method;try{q.open(L,g,E,j.user||c,j.password||c);if(j.withCredentials)q.withCredentials=j.withCredentials;var H=j.headers,O;if(H)for(var P in H)"content-type"===
P.toLowerCase()?O=H[P]:H[P]&&q.setRequestHeader(P,H[P]);O&&!1!==O&&q.setRequestHeader("Content-Type",O);(!H||!("X-Requested-With"in H))&&q.setRequestHeader("X-Requested-With","XMLHttpRequest");m.notify&&m.notify.emit("send",p,w.promise.cancel);q.send(N)}catch(X){w.reject(X)}k(w);q=null;return h?w:w.promise}l.add("native-xhr",function(){return"undefined"!==typeof XMLHttpRequest});l.add("dojo-force-activex-xhr",function(){return l("activex")&&!document.addEventListener&&"file:"===window.location.protocol});
l.add("native-xhr2",function(){if(l("native-xhr")){var a=new XMLHttpRequest;return"undefined"!==typeof a.addEventListener&&("undefined"===typeof opera||"undefined"!==typeof a.upload)}});l.add("native-formdata",function(){return"function"===typeof FormData});var i,n,a,d;l("native-xhr2")?(i=function(){return!this.isFulfilled()},d=function(a,b){b.xhr.abort()},a=function(a,c,d){function e(){c.handleResponse(d)}function f(a){a=new b("Unable to load "+d.url+" status: "+a.target.status,d);c.handleResponse(d,
a)}function j(a){if(a.lengthComputable)d.loaded=a.loaded,d.total=a.total,c.progress(d)}a.addEventListener("load",e,!1);a.addEventListener("error",f,!1);a.addEventListener("progress",j,!1);return function(){a.removeEventListener("load",e,!1);a.removeEventListener("error",f,!1);a.removeEventListener("progress",j,!1)}}):(i=function(a){return a.xhr.readyState},n=function(a){return 4===a.xhr.readyState},d=function(a,b){var c=b.xhr,d=typeof c.abort;("function"===d||"object"===d||"unknown"===d)&&c.abort()});
var c,e={data:null,query:null,sync:!1,method:"GET",headers:{"Content-Type":"application/x-www-form-urlencoded"}};f._create=function(){throw Error("XMLHTTP not available");};if(l("native-xhr")&&!l("dojo-force-activex-xhr"))f._create=function(){return new XMLHttpRequest};else if(l("activex"))try{new ActiveXObject("Msxml2.XMLHTTP"),f._create=function(){return new ActiveXObject("Msxml2.XMLHTTP")}}catch(j){try{new ActiveXObject("Microsoft.XMLHTTP"),f._create=function(){return new ActiveXObject("Microsoft.XMLHTTP")}}catch(p){}}m.addCommonMethods(f);
return f})},"dojo/keys":function(){define("dojo/keys",["./_base/kernel","./sniff"],function(b,k){return b.keys={BACKSPACE:8,TAB:9,CLEAR:12,ENTER:13,SHIFT:16,CTRL:17,ALT:18,META:k("webkit")?91:224,PAUSE:19,CAPS_LOCK:20,ESCAPE:27,SPACE:32,PAGE_UP:33,PAGE_DOWN:34,END:35,HOME:36,LEFT_ARROW:37,UP_ARROW:38,RIGHT_ARROW:39,DOWN_ARROW:40,INSERT:45,DELETE:46,HELP:47,LEFT_WINDOW:91,RIGHT_WINDOW:92,SELECT:93,NUMPAD_0:96,NUMPAD_1:97,NUMPAD_2:98,NUMPAD_3:99,NUMPAD_4:100,NUMPAD_5:101,NUMPAD_6:102,NUMPAD_7:103,NUMPAD_8:104,
NUMPAD_9:105,NUMPAD_MULTIPLY:106,NUMPAD_PLUS:107,NUMPAD_ENTER:108,NUMPAD_MINUS:109,NUMPAD_PERIOD:110,NUMPAD_DIVIDE:111,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,F13:124,F14:125,F15:126,NUM_LOCK:144,SCROLL_LOCK:145,UP_DPAD:175,DOWN_DPAD:176,LEFT_DPAD:177,RIGHT_DPAD:178,copyKey:k("mac")&&!k("air")?k("safari")?91:224:17}})},"dojo/domReady":function(){define(["./has"],function(b){function k(a){f?a(m):i.push(a)}var h=this,m=document,l={loaded:1,complete:1},
o="string"!=typeof m.readyState,f=!!l[m.readyState];if(o)m.readyState="loading";if(!f){var i=[],n=[],a=function(a){a=a||h.event;if(!(f||"readystatechange"==a.type&&!l[m.readyState])){f=1;if(o)m.readyState="complete";for(;i.length;)i.shift()(m)}},d=function(b,c){b.addEventListener(c,a,!1);i.push(function(){b.removeEventListener(c,a,!1)})};if(!b("dom-addeventlistener")){var d=function(b,c){c="on"+c;b.attachEvent(c,a);i.push(function(){b.detachEvent(c,a)})},c=m.createElement("div");try{c.doScroll&&null===
h.frameElement&&n.push(function(){try{return c.doScroll("left"),1}catch(a){}})}catch(e){}}d(m,"DOMContentLoaded");d(h,"load");"onreadystatechange"in m?d(m,"readystatechange"):o||n.push(function(){return l[m.readyState]});if(n.length){var j=function(){if(!f){for(var b=n.length;b--;)if(n[b]()){a("poller");return}setTimeout(j,30)}};j()}}k.load=function(a,b,c){k(c)};return k})},"dojo/_base/lang":function(){define("dojo/_base/lang",["./kernel","../has","../sniff"],function(b,k){k.add("bug-for-in-skips-shadowed",
function(){for(var a in{toString:1})return 0;return 1});var h=k("bug-for-in-skips-shadowed")?"hasOwnProperty.valueOf.isPrototypeOf.propertyIsEnumerable.toLocaleString.toString.constructor".split("."):[],m=h.length,l=function(a,d,c){var e,f=0,i=b.global;if(!c)if(a.length){e=a[f++];try{c=b.scopeMap[e]&&b.scopeMap[e][1]}catch(g){}c=c||(e in i?i[e]:d?i[e]={}:void 0)}else return i;for(;c&&(e=a[f++]);)c=e in c?c[e]:d?c[e]={}:void 0;return c},o=Object.prototype.toString,f=function(a,b,c){return(c||[]).concat(Array.prototype.slice.call(a,
b||0))},i=/\{([^\}]+)\}/g,n={_extraNames:h,_mixin:function(a,b,c){var e,f,i,g={};for(e in b)if(f=b[e],!(e in a)||a[e]!==f&&(!(e in g)||g[e]!==f))a[e]=c?c(f):f;if(k("bug-for-in-skips-shadowed")&&b)for(i=0;i<m;++i)if(e=h[i],f=b[e],!(e in a)||a[e]!==f&&(!(e in g)||g[e]!==f))a[e]=c?c(f):f;return a},mixin:function(a,b){a||(a={});for(var c=1,e=arguments.length;c<e;c++)n._mixin(a,arguments[c]);return a},setObject:function(a,b,c){var e=a.split("."),a=e.pop();return(c=l(e,!0,c))&&a?c[a]=b:void 0},getObject:function(a,
b,c){return l(a.split("."),b,c)},exists:function(a,b){return void 0!==n.getObject(a,!1,b)},isString:function(a){return"string"==typeof a||a instanceof String},isArray:function(a){return a&&(a instanceof Array||"array"==typeof a)},isFunction:function(a){return"[object Function]"===o.call(a)},isObject:function(a){return void 0!==a&&(null===a||"object"==typeof a||n.isArray(a)||n.isFunction(a))},isArrayLike:function(a){return a&&void 0!==a&&!n.isString(a)&&!n.isFunction(a)&&!(a.tagName&&"form"==a.tagName.toLowerCase())&&
(n.isArray(a)||isFinite(a.length))},isAlien:function(a){return a&&!n.isFunction(a)&&/\{\s*\[native code\]\s*\}/.test(""+a)},extend:function(a,b){for(var c=1,e=arguments.length;c<e;c++)n._mixin(a.prototype,arguments[c]);return a},_hitchArgs:function(a,d){var c=n._toArray(arguments,2),e=n.isString(d);return function(){var f=n._toArray(arguments),i=e?(a||b.global)[d]:d;return i&&i.apply(a||this,c.concat(f))}},hitch:function(a,d){if(2<arguments.length)return n._hitchArgs.apply(b,arguments);d||(d=a,a=
null);if(n.isString(d)){a=a||b.global;if(!a[d])throw['lang.hitch: scope["',d,'"] is null (scope="',a,'")'].join("");return function(){return a[d].apply(a,arguments||[])}}return!a?d:function(){return d.apply(a,arguments||[])}},delegate:function(){function a(){}return function(b,c){a.prototype=b;var e=new a;a.prototype=null;c&&n._mixin(e,c);return e}}(),_toArray:k("ie")?function(){function a(a,b,e){e=e||[];for(b=b||0;b<a.length;b++)e.push(a[b]);return e}return function(b){return(b.item?a:f).apply(this,
arguments)}}():f,partial:function(a){return n.hitch.apply(b,[null].concat(n._toArray(arguments)))},clone:function(a){if(!a||"object"!=typeof a||n.isFunction(a))return a;if(a.nodeType&&"cloneNode"in a)return a.cloneNode(!0);if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return RegExp(a);var b,c,e;if(n.isArray(a)){b=[];for(c=0,e=a.length;c<e;++c)c in a&&b.push(n.clone(a[c]))}else b=a.constructor?new a.constructor:{};return n._mixin(b,a,n.clone)},trim:String.prototype.trim?
function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},replace:function(a,b,c){return a.replace(c||i,n.isFunction(b)?b:function(a,c){return n.getObject(c,!1,b)})}};n.mixin(b,n);return n})},"dojo/request/util":function(){define("dojo/request/util","exports,../errors/RequestError,../errors/CancelError,../Deferred,../io-query,../_base/array,../_base/lang".split(","),function(b,k,h,m,l,o,f){function i(a){return n(a)}b.deepCopy=function(a,d){for(var c in d){var e=
a[c],f=d[c];e!==f&&(e&&"object"===typeof e&&f&&"object"===typeof f?b.deepCopy(e,f):a[c]=f)}return a};b.deepCreate=function(a,d){var d=d||{},c=f.delegate(a),e,j;for(e in a)(j=a[e])&&"object"===typeof j&&(c[e]=b.deepCreate(j,d[e]));return b.deepCopy(c,d)};var n=Object.freeze||function(a){return a};b.deferred=function(a,d,c,e,j,l){var g=new m(function(b){d&&d(g,a);return!b||!(b instanceof k)&&!(b instanceof h)?new h("Request canceled",a):b});g.response=a;g.isValid=c;g.isReady=e;g.handleResponse=j;c=
g.then(i).otherwise(function(b){b.response=a;throw b;});b.notify&&c.then(f.hitch(b.notify,"emit","load"),f.hitch(b.notify,"emit","error"));e=c.then(function(a){return a.data||a.text});c=n(f.delegate(e,{response:c}));l&&g.then(function(a){l.call(g,a)},function(b){l.call(g,a,b)});g.promise=c;g.then=c.then;return g};b.addCommonMethods=function(a,b){o.forEach(b||["GET","POST","PUT","DELETE"],function(b){a[("DELETE"===b?"DEL":b).toLowerCase()]=function(d,j){j=f.delegate(j||{});j.method=b;return a(d,j)}})};
b.parseArgs=function(a,b,c){var e=b.data,f=b.query;if(e&&!c&&"object"===typeof e)b.data=l.objectToQuery(e);f?("object"===typeof f&&(f=l.objectToQuery(f)),b.preventCache&&(f+=(f?"&":"")+"request.preventCache="+ +new Date)):b.preventCache&&(f="request.preventCache="+ +new Date);a&&f&&(a+=(~a.indexOf("?")?"&":"?")+f);return{url:a,options:b,getHeader:function(){return null}}};b.checkStatus=function(a){a=a||0;return 200<=a&&300>a||304===a||1223===a||!a}})},"dojo/Evented":function(){define("dojo/Evented",
["./aspect","./on"],function(b,k){function h(){}var m=b.after;h.prototype={on:function(b,h){return k.parse(this,b,h,function(b,i){return m(b,"on"+i,h,!0)})},emit:function(b,h){var f=[this];f.push.apply(f,arguments);return k.emit.apply(k,f)}};return h})},"dojo/mouse":function(){define("dojo/mouse",["./_base/kernel","./on","./has","./dom","./_base/window"],function(b,k,h,m,l){function o(b,i){var h=function(a,d){return k(a,b,function(b){if(i)return i(b,d);if(!m.isDescendant(b.relatedTarget,a))return d.call(this,
b)})};h.bubble=function(a){return o(b,function(b,c){var e=a(b.target),f=b.relatedTarget;if(e&&e!=(f&&1==f.nodeType&&a(f)))return c.call(e,b)})};return h}h.add("dom-quirks",l.doc&&"BackCompat"==l.doc.compatMode);h.add("events-mouseenter",l.doc&&"onmouseenter"in l.doc.createElement("div"));h.add("events-mousewheel",l.doc&&"onmousewheel"in l.doc);l=h("dom-quirks")&&h("ie")||!h("dom-addeventlistener")?{LEFT:1,MIDDLE:4,RIGHT:2,isButton:function(b,i){return b.button&i},isLeft:function(b){return b.button&
1},isMiddle:function(b){return b.button&4},isRight:function(b){return b.button&2}}:{LEFT:0,MIDDLE:1,RIGHT:2,isButton:function(b,i){return b.button==i},isLeft:function(b){return 0==b.button},isMiddle:function(b){return 1==b.button},isRight:function(b){return 2==b.button}};b.mouseButtons=l;b=h("events-mousewheel")?"mousewheel":function(b,i){return k(b,"DOMMouseScroll",function(b){b.wheelDelta=-b.detail;i.call(this,b)})};return{_eventHandler:o,enter:o("mouseover"),leave:o("mouseout"),wheel:b,isLeft:l.isLeft,
isMiddle:l.isMiddle,isRight:l.isRight}})},"dojo/topic":function(){define("dojo/topic",["./Evented"],function(b){var k=new b;return{publish:function(b,m){return k.emit.apply(k,arguments)},subscribe:function(b,m){return k.on.apply(k,arguments)}}})},"dojo/_base/xhr":function(){define("dojo/_base/xhr","./kernel,./sniff,require,../io-query,../dom,../dom-form,./Deferred,./config,./json,./lang,./array,../on,../aspect,../request/watch,../request/xhr,../request/util".split(","),function(b,k,h,m,l,o,f,i,n,
a,d,c,e,j,p,g){b._xhrObj=p._create;var r=b.config;b.objectToQuery=m.objectToQuery;b.queryToObject=m.queryToObject;b.fieldToObject=o.fieldToObject;b.formToObject=o.toObject;b.formToQuery=o.toQuery;b.formToJson=o.toJson;b._blockAsync=!1;var t=b._contentHandlers=b.contentHandlers={text:function(a){return a.responseText},json:function(a){return n.fromJson(a.responseText||null)},"json-comment-filtered":function(a){var a=a.responseText,b=a.indexOf("/*"),c=a.lastIndexOf("*/");if(-1==b||-1==c)throw Error("JSON was not comment filtered");
return n.fromJson(a.substring(b+2,c))},javascript:function(a){return b.eval(a.responseText)},xml:function(a){var b=a.responseXML;if(k("ie")&&(!b||!b.documentElement)){var c=function(a){return"MSXML"+a+".DOMDocument"},c=["Microsoft.XMLDOM",c(6),c(4),c(3),c(2)];d.some(c,function(c){try{var d=new ActiveXObject(c);d.async=!1;d.loadXML(a.responseText);b=d}catch(e){return!1}return!0})}return b},"json-comment-optional":function(a){return a.responseText&&/^[^{\[]*\/\*/.test(a.responseText)?t["json-comment-filtered"](a):
t.json(a)}};b._ioSetArgs=function(c,d,e,g){var j={args:c,url:c.url},i=null;if(c.form){var i=l.byId(c.form),h=i.getAttributeNode("action");j.url=j.url||(h?h.value:null);i=o.toObject(i)}h=[{}];i&&h.push(i);c.content&&h.push(c.content);c.preventCache&&h.push({"dojo.preventCache":(new Date).valueOf()});j.query=m.objectToQuery(a.mixin.apply(null,h));j.handleAs=c.handleAs||"text";var n=new f(function(a){a.canceled=!0;d&&d(a);var b=a.ioArgs.error;if(!b)b=Error("request cancelled"),b.dojoType="cancel",a.ioArgs.error=
b;return b});n.addCallback(e);var k=c.load;k&&a.isFunction(k)&&n.addCallback(function(a){return k.call(c,a,j)});var p=c.error;p&&a.isFunction(p)&&n.addErrback(function(a){return p.call(c,a,j)});var s=c.handle;s&&a.isFunction(s)&&n.addBoth(function(a){return s.call(c,a,j)});n.addErrback(function(a){return g(a,n)});r.ioPublish&&b.publish&&!1!==j.args.ioPublish&&(n.addCallbacks(function(a){b.publish("/dojo/io/load",[n,a]);return a},function(a){b.publish("/dojo/io/error",[n,a]);return a}),n.addBoth(function(a){b.publish("/dojo/io/done",
[n,a]);return a}));n.ioArgs=j;return n};var u=function(a){a=t[a.ioArgs.handleAs](a.ioArgs.xhr);return void 0===a?null:a},s=function(a,b){b.ioArgs.args.failOk||console.error(a);return a},w=function(a){0>=q&&(q=0,r.ioPublish&&b.publish&&(!a||a&&!1!==a.ioArgs.args.ioPublish)&&b.publish("/dojo/io/stop"))},q=0;e.after(j,"_onAction",function(){q-=1});e.after(j,"_onInFlight",w);b._ioCancelAll=j.cancelAll;b._ioNotifyStart=function(a){r.ioPublish&&b.publish&&!1!==a.ioArgs.args.ioPublish&&(q||b.publish("/dojo/io/start"),
q+=1,b.publish("/dojo/io/send",[a]))};b._ioWatch=function(b,c,d,e){b.ioArgs.options=b.ioArgs.args;a.mixin(b,{response:b.ioArgs,isValid:function(){return c(b)},isReady:function(){return d(b)},handleResponse:function(){return e(b)}});j(b);w(b)};b._ioAddQueryToUrl=function(a){if(a.query.length)a.url+=(-1==a.url.indexOf("?")?"?":"&")+a.query,a.query=null};b.xhr=function(a,c,d){var e,g=b._ioSetArgs(c,function(){e&&e.cancel()},u,s),f=g.ioArgs;"postData"in c?f.query=c.postData:"putData"in c?f.query=c.putData:
"rawBody"in c?f.query=c.rawBody:(2<arguments.length&&!d||-1==="POST|PUT".indexOf(a.toUpperCase()))&&b._ioAddQueryToUrl(f);var j={method:a,handleAs:"text",timeout:c.timeout,withCredentials:c.withCredentials,ioArgs:f};if("undefined"!==typeof c.headers)j.headers=c.headers;if("undefined"!==typeof c.contentType){if(!j.headers)j.headers={};j.headers["Content-Type"]=c.contentType}if("undefined"!==typeof f.query)j.data=f.query;if("undefined"!==typeof c.sync)j.sync=c.sync;b._ioNotifyStart(g);try{e=p(f.url,
j,!0)}catch(i){return g.cancel(),g}g.ioArgs.xhr=e.response.xhr;e.then(function(){g.resolve(g)}).otherwise(function(a){f.error=a;if(a.response)a.status=a.response.status,a.responseText=a.response.text,a.xhr=a.response.xhr;g.reject(a)});return g};b.xhrGet=function(a){return b.xhr("GET",a)};b.rawXhrPost=b.xhrPost=function(a){return b.xhr("POST",a,!0)};b.rawXhrPut=b.xhrPut=function(a){return b.xhr("PUT",a,!0)};b.xhrDelete=function(a){return b.xhr("DELETE",a)};b._isDocumentOk=function(a){return g.checkStatus(a.status)};
b._getText=function(a){var c;b.xhrGet({url:a,sync:!0,load:function(a){c=a}});return c};a.mixin(b.xhr,{_xhrObj:b._xhrObj,fieldToObject:o.fieldToObject,formToObject:o.toObject,objectToQuery:m.objectToQuery,formToQuery:o.toQuery,formToJson:o.toJson,queryToObject:m.queryToObject,contentHandlers:t,_ioSetArgs:b._ioSetArgs,_ioCancelAll:b._ioCancelAll,_ioNotifyStart:b._ioNotifyStart,_ioWatch:b._ioWatch,_ioAddQueryToUrl:b._ioAddQueryToUrl,_isDocumentOk:b._isDocumentOk,_getText:b._getText,get:b.xhrGet,post:b.xhrPost,
put:b.xhrPut,del:b.xhrDelete});return b.xhr})},"dojo/_base/unload":function(){define(["./kernel","./lang","../on"],function(b,k,h){var m=window,l={addOnWindowUnload:function(l,f){if(!b.windowUnloaded)h(m,"unload",b.windowUnloaded=function(){});h(m,"unload",k.hitch(l,f))},addOnUnload:function(b,f){h(m,"beforeunload",k.hitch(b,f))}};b.addOnWindowUnload=l.addOnWindowUnload;b.addOnUnload=l.addOnUnload;return l})},"dojo/Deferred":function(){define(["./has","./_base/lang","./errors/CancelError","./promise/Promise",
"require"],function(b,k,h,m,l){var o=Object.freeze||function(){},f=function(a,b,d,f){for(var g=0;g<a.length;g++)i(a[g],b,d,f)},i=function(b,d,f){var i=b[d],g=b.deferred;if(i)try{var h=i(f);0===d?"undefined"!==typeof h&&a(g,d,h):h&&"function"===typeof h.then?(b.cancel=h.cancel,h.then(n(g,1),n(g,2),n(g,0))):a(g,1,h)}catch(l){a(g,2,l)}else a(g,d,f)},n=function(b,d){return function(f){a(b,d,f)}},a=function(a,b,d){if(!a.isCanceled())switch(b){case 0:a.progress(d);break;case 1:a.resolve(d);break;case 2:a.reject(d)}},
d=function(a){var b=this.promise=new m,j=this,n,g,l=!1,k=[];this.isResolved=b.isResolved=function(){return 1===n};this.isRejected=b.isRejected=function(){return 2===n};this.isFulfilled=b.isFulfilled=function(){return!!n};this.isCanceled=b.isCanceled=function(){return l};this.progress=function(a,c){if(n){if(!0===c)throw Error("This deferred has already been fulfilled.");return b}f(k,0,a,null,j);return b};this.resolve=function(a,c){if(n){if(!0===c)throw Error("This deferred has already been fulfilled.");
return b}f(k,n=1,g=a,null,j);k=null;return b};var u=this.reject=function(a,c){if(n){if(!0===c)throw Error("This deferred has already been fulfilled.");return b}f(k,n=2,g=a,void 0,j);k=null;return b};this.then=b.then=function(a,c,f){var j=[f,a,c];j.cancel=b.cancel;j.deferred=new d(function(a){return j.cancel&&j.cancel(a)});n&&!k?i(j,n,g,void 0):k.push(j);return j.deferred.promise};this.cancel=b.cancel=function(b,d){if(n){if(!0===d)throw Error("This deferred has already been fulfilled.");}else{if(a)var e=
a(b),b="undefined"===typeof e?b:e;l=!0;if(n){if(2===n&&g===b)return b}else return"undefined"===typeof b&&(b=new h),u(b),b}};o(b)};d.prototype.toString=function(){return"[object Deferred]"};l&&l(d);return d})},"dojo/_base/NodeList":function(){define("dojo/_base/NodeList",["./kernel","../query","./array","./html","../NodeList-dom"],function(b,k,h){var k=k.NodeList,m=k.prototype;m.connect=k._adaptAsForEach(function(){return b.connect.apply(this,arguments)});m.coords=k._adaptAsMap(b.coords);k.events=
"blur,focus,change,click,error,keydown,keypress,keyup,load,mousedown,mouseenter,mouseleave,mousemove,mouseout,mouseover,mouseup,submit".split(",");h.forEach(k.events,function(b){var h="on"+b;m[h]=function(b,i){return this.connect(h,b,i)}});return b.NodeList=k})},"dojo/_base/Color":function(){define(["./kernel","./lang","./array","./config"],function(b,k,h,m){var l=b.Color=function(b){b&&this.setColor(b)};l.named={black:[0,0,0],silver:[192,192,192],gray:[128,128,128],white:[255,255,255],maroon:[128,
0,0],red:[255,0,0],purple:[128,0,128],fuchsia:[255,0,255],green:[0,128,0],lime:[0,255,0],olive:[128,128,0],yellow:[255,255,0],navy:[0,0,128],blue:[0,0,255],teal:[0,128,128],aqua:[0,255,255],transparent:m.transparentColor||[0,0,0,0]};k.extend(l,{r:255,g:255,b:255,a:1,_set:function(b,f,i,h){this.r=b;this.g=f;this.b=i;this.a=h},setColor:function(b){k.isString(b)?l.fromString(b,this):k.isArray(b)?l.fromArray(b,this):(this._set(b.r,b.g,b.b,b.a),b instanceof l||this.sanitize());return this},sanitize:function(){return this},
toRgb:function(){return[this.r,this.g,this.b]},toRgba:function(){return[this.r,this.g,this.b,this.a]},toHex:function(){return"#"+h.map(["r","g","b"],function(b){b=this[b].toString(16);return 2>b.length?"0"+b:b},this).join("")},toCss:function(b){var f=this.r+", "+this.g+", "+this.b;return(b?"rgba("+f+", "+this.a:"rgb("+f)+")"},toString:function(){return this.toCss(!0)}});l.blendColors=b.blendColors=function(b,f,i,n){var a=n||new l;h.forEach(["r","g","b","a"],function(d){a[d]=b[d]+(f[d]-b[d])*i;"a"!=
d&&(a[d]=Math.round(a[d]))});return a.sanitize()};l.fromRgb=b.colorFromRgb=function(b,f){var i=b.toLowerCase().match(/^rgba?\(([\s\.,0-9]+)\)/);return i&&l.fromArray(i[1].split(/\s*,\s*/),f)};l.fromHex=b.colorFromHex=function(b,f){var i=f||new l,n=4==b.length?4:8,a=(1<<n)-1,b=Number("0x"+b.substr(1));if(isNaN(b))return null;h.forEach(["b","g","r"],function(d){var c=b&a;b>>=n;i[d]=4==n?17*c:c});i.a=1;return i};l.fromArray=b.colorFromArray=function(b,f){var i=f||new l;i._set(Number(b[0]),Number(b[1]),
Number(b[2]),Number(b[3]));if(isNaN(i.a))i.a=1;return i.sanitize()};l.fromString=b.colorFromString=function(b,f){var i=l.named[b];return i&&l.fromArray(i,f)||l.fromRgb(b,f)||l.fromHex(b,f)};return l})},"dojo/selector/_loader":function(){define(["../has","require"],function(b,k){var h=document.createElement("div");b.add("dom-qsa2.1",!!h.querySelectorAll);b.add("dom-qsa3",function(){try{return h.innerHTML="<p class='TEST'></p>",1==h.querySelectorAll(".TEST:empty").length}catch(b){}});var m;return{load:function(h,
o,f){var i=k,h="default"==h?b("config-selectorEngine")||"css3":h,h="css2"==h||"lite"==h?"./lite":"css2.1"==h?b("dom-qsa2.1")?"./lite":"./acme":"css3"==h?b("dom-qsa3")?"./lite":"./acme":"acme"==h?"./acme":(i=o)&&h;if("?"==h.charAt(h.length-1))var h=h.substring(0,h.length-1),n=!0;if(n&&(b("dom-compliant-qsa")||m))return f(m);i([h],function(a){"./lite"!=h&&(m=a);f(a)})}}})},"dojo/promise/Promise":function(){define(["../_base/lang"],function(b){function k(){throw new TypeError("abstract");}return b.extend(function(){},
{then:function(){k()},cancel:function(){k()},isResolved:function(){k()},isRejected:function(){k()},isFulfilled:function(){k()},isCanceled:function(){k()},always:function(b){return this.then(b,b)},otherwise:function(b){return this.then(null,b)},trace:function(){return this},traceRejected:function(){return this},toString:function(){return"[object Promise]"}})})},"dojo/request/watch":function(){define("./util,../errors/RequestTimeoutError,../errors/CancelError,../_base/array,../_base/window,../has!host-browser?dom-addeventlistener?:../on:".split(","),
function(b,k,h,m,l,o){function f(){for(var b=+new Date,c=0,e;c<a.length&&(e=a[c]);c++){var f=e.response,h=f.options;if(e.isCanceled&&e.isCanceled()||e.isValid&&!e.isValid(f))a.splice(c--,1),i._onAction&&i._onAction();else if(e.isReady&&e.isReady(f))a.splice(c--,1),e.handleResponse(f),i._onAction&&i._onAction();else if(e.startTime&&e.startTime+(h.timeout||0)<b)a.splice(c--,1),e.cancel(new k("Timeout exceeded",f)),i._onAction&&i._onAction()}i._onInFlight&&i._onInFlight(e);a.length||(clearInterval(n),
n=null)}function i(b){if(b.response.options.timeout)b.startTime=+new Date;b.isFulfilled()||(a.push(b),n||(n=setInterval(f,50)),b.response.options.sync&&f())}var n=null,a=[];i.cancelAll=function(){try{m.forEach(a,function(a){try{a.cancel(new h("All requests canceled."))}catch(b){}})}catch(b){}};l&&o&&l.doc.attachEvent&&o(l.global,"unload",function(){i.cancelAll()});return i})},"dojo/selector/lite":function(){define(["../has","../_base/kernel"],function(b,k){var h=document.createElement("div"),m=h.matchesSelector||
h.webkitMatchesSelector||h.mozMatchesSelector||h.msMatchesSelector||h.oMatchesSelector,l=h.querySelectorAll,o=/([^\s,](?:"(?:\\.|[^"])+"|'(?:\\.|[^'])+'|[^,])*)/g;b.add("dom-matches-selector",!!m);b.add("dom-qsa",!!l);var f=function(b,c){if(a&&-1<b.indexOf(","))return a(b,c);var e=c?c.ownerDocument||c:k.doc||document,j=(l?/^([\w]*)#([\w\-]+$)|^(\.)([\w\-\*]+$)|^(\w+$)/:/^([\w]*)#([\w\-]+)(?:\s+(.*))?$|(?:^|(>|.+\s+))([\w\-\*]+)(\S*$)/).exec(b),c=c||e;if(j){if(j[2]){var h=k.byId?k.byId(j[2]):e.getElementById(j[2]);
if(!h||j[1]&&j[1]!=h.tagName.toLowerCase())return[];if(c!=e)for(e=h;e!=c;)if(e=e.parentNode,!e)return[];return j[3]?f(j[3],h):[h]}if(j[3]&&c.getElementsByClassName)return c.getElementsByClassName(j[4]);if(j[5])if(h=c.getElementsByTagName(j[5]),j[4]||j[6])b=(j[4]||"")+j[6];else return h}if(l)return 1===c.nodeType&&"object"!==c.nodeName.toLowerCase()?i(c,b,c.querySelectorAll):c.querySelectorAll(b);h||(h=c.getElementsByTagName("*"));for(var j=[],e=0,g=h.length;e<g;e++){var m=h[e];1==m.nodeType&&n(m,
b,c)&&j.push(m)}return j},i=function(a,b,e){var f=a,i=a.getAttribute("id"),g=i||"__dojo__",h=a.parentNode,n=/^\s*[+~]/.test(b);if(n&&!h)return[];i?g=g.replace(/'/g,"\\$&"):a.setAttribute("id",g);if(n&&h)a=a.parentNode;b=b.match(o);for(h=0;h<b.length;h++)b[h]="[id='"+g+"'] "+b[h];b=b.join(",");try{return e.call(a,b)}finally{i||f.removeAttribute("id")}};if(!b("dom-matches-selector"))var n=function(){function a(b,c,d){var e=c.charAt(0);if('"'==e||"'"==e)c=c.slice(1,-1);var c=c.replace(/\\/g,""),f=n[d||
""];return function(a){return(a=a.getAttribute(b))&&f(a,c)}}function b(a){return function(b,c){for(;(b=b.parentNode)!=c;)if(a(b,c))return!0}}function e(a){return function(b,c){b=b.parentNode;return a?b!=c&&a(b,c):b==c}}function f(a,b){return a?function(c,d){return b(c)&&a(c,d)}:b}var i="div"==h.tagName?"toLowerCase":"toUpperCase",g={"":function(a){a=a[i]();return function(b){return b.tagName==a}},".":function(a){var b=" "+a+" ";return function(c){return-1<c.className.indexOf(a)&&-1<(" "+c.className+
" ").indexOf(b)}},"#":function(a){return function(b){return b.id==a}}},n={"^=":function(a,b){return 0==a.indexOf(b)},"*=":function(a,b){return-1<a.indexOf(b)},"$=":function(a,b){return a.substring(a.length-b.length,a.length)==b},"~=":function(a,b){return-1<(" "+a+" ").indexOf(" "+b+" ")},"|=":function(a,b){return 0==(a+"-").indexOf(b+"-")},"=":function(a,b){return a==b},"":function(){return!0}},k={};return function(i,h,n){var l=k[h];if(!l){if(h.replace(/(?:\s*([> ])\s*)|(#|\.)?((?:\\.|[\w-])+)|\[\s*([\w-]+)\s*(.?=)?\s*("(?:\\.|[^"])+"|'(?:\\.|[^'])+'|(?:\\.|[^\]])*)\s*\]/g,
function(i,h,n,k,m,p,o){k?l=f(l,g[n||""](k.replace(/\\/g,""))):h?l=(" "==h?b:e)(l):m&&(l=f(l,a(m,o,p)));return""}))throw Error("Syntax error in query");if(!l)return!0;k[h]=l}return l(i,n)}}();if(!b("dom-qsa"))var a=function(a,b){for(var e=a.match(o),j=[],i=0;i<e.length;i++){a=new String(e[i].replace(/\s*$/,""));a.indexOf=escape;for(var g=f(a,b),h=0,n=g.length;h<n;h++){var k=g[h];j[k.sourceIndex]=k}}e=[];for(i in j)e.push(j[i]);return e};f.match=m?function(a,b,e){return e&&9!=e.nodeType?i(e,b,function(b){return m.call(a,
b)}):m.call(a,b)}:n;return f})},"dojo/on":function(){define(["./has!dom-addeventlistener?:./aspect","./_base/kernel","./has"],function(b,k,h){function m(a,b,d,e,f){if(e=b.match(/(.*):(.*)/))return b=e[2],e=e[1],i.selector(e,b).call(f,a,d);h("touch")&&(n.test(b)&&(d=N(d)),!h("event-orientationchange")&&"orientationchange"==b&&(b="resize",a=window,d=N(d)));j&&(d=j(d));if(a.addEventListener){var g=b in c,k=g?c[b]:b;a.addEventListener(k,d,g);return{remove:function(){a.removeEventListener(k,d,g)}}}if(t&&
a.attachEvent)return t(a,"on"+b,d);throw Error("Target must be an event emitter");}function l(){this.cancelable=!1}function o(){this.bubbles=!1}var f=window.ScriptEngineMajorVersion;h.add("jscript",f&&f()+ScriptEngineMinorVersion()/10);h.add("event-orientationchange",h("touch")&&!h("android"));h.add("event-stopimmediatepropagation",window.Event&&!!window.Event.prototype&&!!window.Event.prototype.stopImmediatePropagation);var i=function(a,b,c,d){return"function"==typeof a.on&&"function"!=typeof b?
a.on(b,c):i.parse(a,b,c,m,d,this)};i.pausable=function(a,b,c,d){var e,a=i(a,b,function(){if(!e)return c.apply(this,arguments)},d);a.pause=function(){e=!0};a.resume=function(){e=!1};return a};i.once=function(a,b,c){var d=i(a,b,function(){d.remove();return c.apply(this,arguments)});return d};i.parse=function(a,b,c,d,e,f){if(b.call)return b.call(f,a,c);if(-1<b.indexOf(",")){for(var b=b.split(/\s*,\s*/),g=[],j=0,i;i=b[j++];)g.push(d(a,i,c,e,f));g.remove=function(){for(var a=0;a<g.length;a++)g[a].remove()};
return g}return d(a,b,c,e,f)};var n=/^touch/;i.selector=function(a,b,c){return function(d,e){function f(b){for(g=g&&g.matches?g:k.query;!g.matches(b,a,d);)if(b==d||!1===c||!(b=b.parentNode)||1!=b.nodeType)return;return b}var g="function"==typeof a?{matches:a}:this,j=b.bubble;return j?i(d,j(f),e):i(d,b,function(a){var b=f(a.target);return b&&e.call(b,a)})}};var a=[].slice,d=i.emit=function(b,c,d){var e=a.call(arguments,2),g="on"+c;if("parentNode"in b){var f=e[0]={},j;for(j in d)f[j]=d[j];f.preventDefault=
l;f.stopPropagation=o;f.target=b;f.type=c;d=f}do b[g]&&b[g].apply(b,e);while(d&&d.bubbles&&(b=b.parentNode));return d&&d.cancelable&&d},c={};if(!h("event-stopimmediatepropagation"))var e=function(){this.modified=this.immediatelyStopped=!0},j=function(a){return function(b){if(!b.immediatelyStopped)return b.stopImmediatePropagation=e,a.apply(this,arguments)}};if(h("dom-addeventlistener"))c={focusin:"focus",focusout:"blur"},i.emit=function(a,b,c){if(a.dispatchEvent&&document.createEvent){var e=a.ownerDocument.createEvent("HTMLEvents");
e.initEvent(b,!!c.bubbles,!!c.cancelable);for(var f in c)f in e||(e[f]=c[f]);return a.dispatchEvent(e)&&e}return d.apply(i,arguments)};else{i._fixEvent=function(a,b){if(!a)a=(b&&(b.ownerDocument||b.document||b).parentWindow||window).event;if(!a)return a;p&&a.type==p.type&&(a=p);if(!a.target){a.target=a.srcElement;a.currentTarget=b||a.srcElement;if("mouseover"==a.type)a.relatedTarget=a.fromElement;if("mouseout"==a.type)a.relatedTarget=a.toElement;if(!a.stopPropagation)a.stopPropagation=u,a.preventDefault=
s;switch(a.type){case "keypress":var c="charCode"in a?a.charCode:a.keyCode;10==c?(c=0,a.keyCode=13):13==c||27==c?c=0:3==c&&(c=99);a.charCode=c;c=a;c.keyChar=c.charCode?String.fromCharCode(c.charCode):"";c.charOrCode=c.keyChar||c.keyCode}}return a};var p,g=function(a){this.handle=a};g.prototype.remove=function(){delete _dojoIEListeners_[this.handle]};var r=function(a){return function(b){var b=i._fixEvent(b,this),c=a.call(this,b);b.modified&&(p||setTimeout(function(){p=null}),p=b);return c}},t=function(a,
c,d){d=r(d);if(((a.ownerDocument?a.ownerDocument.parentWindow:a.parentWindow||a.window||window)!=top||5.8>h("jscript"))&&!h("config-_allow_leaks")){"undefined"==typeof _dojoIEListeners_&&(_dojoIEListeners_=[]);var e=a[c];if(!e||!e.listeners){var f=e,e=Function("event","var callee = arguments.callee; for(var i = 0; i<callee.listeners.length; i++){var listener = _dojoIEListeners_[callee.listeners[i]]; if(listener){listener.call(this,event);}}");e.listeners=[];a[c]=e;e.global=this;f&&e.listeners.push(_dojoIEListeners_.push(f)-
1)}e.listeners.push(a=e.global._dojoIEListeners_.push(d)-1);return new g(a)}return b.after(a,c,d,!0)},u=function(){this.cancelBubble=!0},s=i._preventDefault=function(){this.bubbledKeyCode=this.keyCode;if(this.ctrlKey)try{this.keyCode=0}catch(a){}this.defaultPrevented=!0;this.returnValue=!1}}if(h("touch"))var w=function(){},q=window.orientation,N=function(a){return function(b){var c=b.corrected;if(!c){var d=b.type;try{delete b.type}catch(e){}b.type?(w.prototype=b,c=new w,c.preventDefault=function(){b.preventDefault()},
c.stopPropagation=function(){b.stopPropagation()}):(c=b,c.type=d);b.corrected=c;if("resize"==d){if(q==window.orientation)return null;q=window.orientation;c.type="orientationchange";return a.call(this,c)}if(!("rotation"in c))c.rotation=0,c.scale=1;var d=c.changedTouches[0],f;for(f in d)delete c[f],c[f]=d[f]}return a.call(this,c)}};return i})},"dojo/_base/sniff":function(){define(["./kernel","./lang","../sniff"],function(b,k,h){b._name="browser";k.mixin(b,{isBrowser:!0,isFF:h("ff"),isIE:h("ie"),isKhtml:h("khtml"),
isWebKit:h("webkit"),isMozilla:h("mozilla"),isMoz:h("mozilla"),isOpera:h("opera"),isSafari:h("safari"),isChrome:h("chrome"),isMac:h("mac"),isIos:h("ios"),isAndroid:h("android"),isWii:h("wii"),isQuirks:h("quirks"),isAir:h("air")});b.locale=b.locale||(h("ie")?navigator.userLanguage:navigator.language).toLowerCase();return h})},"dojo/errors/create":function(){define(["../_base/lang"],function(b){return function(k,h,m,l){var m=m||Error,o=function(b){if(m===Error){Error.captureStackTrace&&Error.captureStackTrace(this,
o);var i=Error.call(this,b),n;for(n in i)i.hasOwnProperty(n)&&(this[n]=i[n]);this.message=b;this.stack=i.stack}else m.apply(this,arguments);h&&h.apply(this,arguments)};o.prototype=b.delegate(m.prototype,l);o.prototype.name=k;return o.prototype.constructor=o}})},"dojo/_base/array":function(){define(["./kernel","../has","./lang"],function(b,k,h){function m(a){return f[a]=new Function("item","index","array",a)}function l(a){var b=!a;return function(c,e,j){var i=0,g=c&&c.length||0,h;g&&"string"==typeof c&&
(c=c.split(""));"string"==typeof e&&(e=f[e]||m(e));if(j)for(;i<g;++i){if(h=!e.call(j,c[i],i,c),a^h)return!h}else for(;i<g;++i)if(h=!e(c[i],i,c),a^h)return!h;return b}}function o(a){var b=1,c=0,e=0;a||(b=c=e=-1);return function(f,h,g,k){if(k&&0<b)return n.lastIndexOf(f,h,g);var k=f&&f.length||0,l=a?k+e:c;g===i?g=a?c:k+e:0>g?(g=k+g,0>g&&(g=c)):g=g>=k?k+e:g;for(k&&"string"==typeof f&&(f=f.split(""));g!=l;g+=b)if(f[g]==h)return g;return-1}}var f={},i,n={every:l(!1),some:l(!0),indexOf:o(!0),lastIndexOf:o(!1),
forEach:function(a,b,c){var e=0,i=a&&a.length||0;i&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=f[b]||m(b));if(c)for(;e<i;++e)b.call(c,a[e],e,a);else for(;e<i;++e)b(a[e],e,a)},map:function(a,b,c,e){var i=0,h=a&&a.length||0,e=new (e||Array)(h);h&&"string"==typeof a&&(a=a.split(""));"string"==typeof b&&(b=f[b]||m(b));if(c)for(;i<h;++i)e[i]=b.call(c,a[i],i,a);else for(;i<h;++i)e[i]=b(a[i],i,a);return e},filter:function(a,b,c){var e=0,i=a&&a.length||0,h=[],g;i&&"string"==typeof a&&(a=a.split(""));
"string"==typeof b&&(b=f[b]||m(b));if(c)for(;e<i;++e)g=a[e],b.call(c,g,e,a)&&h.push(g);else for(;e<i;++e)g=a[e],b(g,e,a)&&h.push(g);return h},clearCache:function(){f={}}};h.mixin(b,n);return n})},"dojo/_base/json":function(){define(["./kernel","../json"],function(b,k){b.fromJson=function(b){return eval("("+b+")")};b._escapeString=k.stringify;b.toJsonIndentStr="\t";b.toJson=function(h,m){return k.stringify(h,function(b,h){if(h){var f=h.__json__||h.json;if("function"==typeof f)return f.call(h)}return h},
m&&b.toJsonIndentStr)};return b})},"dojo/_base/window":function(){define("dojo/_base/window",["./kernel","./lang","../sniff"],function(b,k,h){var m={global:b.global,doc:this.document||null,body:function(h){h=h||b.doc;return h.body||h.getElementsByTagName("body")[0]},setContext:function(h,k){b.global=m.global=h;b.doc=m.doc=k},withGlobal:function(h,k,f,i){var n=b.global;try{return b.global=m.global=h,m.withDoc.call(null,h.document,k,f,i)}finally{b.global=m.global=n}},withDoc:function(k,o,f,i){var n=
m.doc,a=h("quirks"),d=h("ie"),c,e,j;try{b.doc=m.doc=k;b.isQuirks=h.add("quirks","BackCompat"==b.doc.compatMode,!0,!0);if(h("ie")&&(j=k.parentWindow)&&j.navigator)c=parseFloat(j.navigator.appVersion.split("MSIE ")[1])||void 0,(e=k.documentMode)&&5!=e&&Math.floor(c)!=e&&(c=e),b.isIE=h.add("ie",c,!0,!0);f&&"string"==typeof o&&(o=f[o]);return o.apply(f,i||[])}finally{b.doc=m.doc=n,b.isQuirks=h.add("quirks",a,!0,!0),b.isIE=h.add("ie",d,!0,!0)}}};k.mixin(b,m);return m})},"dojo/dom-class":function(){define(["./_base/lang",
"./_base/array","./dom"],function(b,k,h){function m(b){if("string"==typeof b||b instanceof String){if(b&&!o.test(b))return f[0]=b,f;b=b.split(o);b.length&&!b[0]&&b.shift();b.length&&!b[b.length-1]&&b.pop();return b}return!b?[]:k.filter(b,function(a){return a})}var l,o=/\s+/,f=[""],i={};return l={contains:function(b,a){return 0<=(" "+h.byId(b).className+" ").indexOf(" "+a+" ")},add:function(b,a){var b=h.byId(b),a=m(a),d=b.className,c,d=d?" "+d+" ":" ";c=d.length;for(var e=0,f=a.length,i;e<f;++e)(i=
a[e])&&0>d.indexOf(" "+i+" ")&&(d+=i+" ");c<d.length&&(b.className=d.substr(1,d.length-2))},remove:function(f,a){var f=h.byId(f),d;if(void 0!==a){a=m(a);d=" "+f.className+" ";for(var c=0,e=a.length;c<e;++c)d=d.replace(" "+a[c]+" "," ");d=b.trim(d)}else d="";f.className!=d&&(f.className=d)},replace:function(b,a,d){b=h.byId(b);i.className=b.className;l.remove(i,d);l.add(i,a);b.className!==i.className&&(b.className=i.className)},toggle:function(b,a,d){b=h.byId(b);if(void 0===d)for(var a=m(a),c=0,e=a.length,
f;c<e;++c)f=a[c],l[l.contains(b,f)?"remove":"add"](b,f);else l[d?"add":"remove"](b,a);return d}}})},"dojo/_base/config":function(){define(["../has","require"],function(b,k){var h={},m=k.rawConfig,l;for(l in m)h[l]=m[l];return h})},"dojo/_base/event":function(){define("dojo/_base/event",["./kernel","../on","../has","../dom-geometry"],function(b,k,h,m){if(k._fixEvent){var l=k._fixEvent;k._fixEvent=function(b,i){(b=l(b,i))&&m.normalizeEvent(b);return b}}var o={fix:function(b,i){return k._fixEvent?k._fixEvent(b,
i):b},stop:function(b){h("dom-addeventlistener")||b&&b.preventDefault?(b.preventDefault(),b.stopPropagation()):(b=b||window.event,b.cancelBubble=!0,k._preventDefault.call(b))}};b.fixEvent=o.fix;b.stopEvent=o.stop;return o})},"dojo/main":function(){define("./_base/kernel,./has,require,./sniff,./_base/lang,./_base/array,./_base/config,./ready,./_base/declare,./_base/connect,./_base/Deferred,./_base/json,./_base/Color,require,./_base/browser,require".split(","),function(b,k,h,m,l,o,f){f.isDebug&&h(["./_firebug/firebug"]);
return b})},"dojo/sniff":function(){define(["./has"],function(b){var k=navigator,h=k.userAgent,k=k.appVersion,m=parseFloat(k);b.add("air",0<=h.indexOf("AdobeAIR"));b.add("khtml",0<=k.indexOf("Konqueror")?m:void 0);b.add("webkit",parseFloat(h.split("WebKit/")[1])||void 0);b.add("chrome",parseFloat(h.split("Chrome/")[1])||void 0);b.add("safari",0<=k.indexOf("Safari")&&!b("chrome")?parseFloat(k.split("Version/")[1]):void 0);b.add("mac",0<=k.indexOf("Macintosh"));b.add("quirks","BackCompat"==document.compatMode);
b.add("ios",/iPhone|iPod|iPad/.test(h));b.add("android",parseFloat(h.split("Android ")[1])||void 0);if(!b("webkit")){0<=h.indexOf("Opera")&&b.add("opera",9.8<=m?parseFloat(h.split("Version/")[1])||m:m);0<=h.indexOf("Gecko")&&!b("khtml")&&!b("webkit")&&b.add("mozilla",m);b("mozilla")&&b.add("ff",parseFloat(h.split("Firefox/")[1]||h.split("Minefield/")[1])||void 0);if(document.all&&!b("opera"))h=parseFloat(k.split("MSIE ")[1])||void 0,(k=document.documentMode)&&5!=k&&Math.floor(h)!=k&&(h=k),b.add("ie",
h);b.add("wii","undefined"!=typeof opera&&opera.wiiremote)}return b})},"dojo/request/handlers":function(){define(["../json","../_base/kernel","../_base/array","../has"],function(b,k,h,m){function l(b){var a=i[b.options.handleAs];b.data=a?a(b):b.data||b.text;return b}m.add("activex","undefined"!==typeof ActiveXObject);var o;if(m("activex")){var f=["Msxml2.DOMDocument.6.0","Msxml2.DOMDocument.4.0","MSXML2.DOMDocument.3.0","MSXML.DOMDocument"];o=function(b){var a=b.data;if(!a||!a.documentElement){var d=
b.text;h.some(f,function(b){try{var e=new ActiveXObject(b);e.async=!1;e.loadXML(d);a=e}catch(f){return!1}return!0})}return a}}var i={javascript:function(b){return k.eval(b.text||"")},json:function(f){return b.parse(f.text||null)},xml:o};l.register=function(b,a){i[b]=a};return l})},"dojo/ready":function(){define("dojo/ready",["./_base/kernel","./has","require","./domReady","./_base/lang"],function(b,k,h,m,l){var o=0,f,i=[],n=0,a=function(){if(o&&!n&&i.length){n=1;var b=i.shift();try{b()}finally{n=
0}n=0;i.length&&f(a)}};h.on("idle",a);f=function(){h.idle()&&a()};var k=b.ready=b.addOnLoad=function(a,d,h){var k=l._toArray(arguments);"number"!=typeof a?(h=d,d=a,a=1E3):k.shift();h=h?l.hitch.apply(b,k):function(){d()};h.priority=a;for(k=0;k<i.length&&a>=i[k].priority;k++);i.splice(k,0,h);f()},d=b.config.addOnLoad;if(d)k[l.isArray(d)?"apply":"call"](b,d);m(function(){o=1;b._postLoad=b.config.afterOnLoad=!0;i.length&&f(a)});return k})},"dojo/aspect":function(){define("dojo/aspect",[],function(){function b(b,
f,a,d){var c=b[f],e="around"==f,h;if(e){var k=a(function(){return c.advice(this,arguments)});h={remove:function(){h.cancelled=!0},advice:function(a,b){return h.cancelled?c.advice(a,b):k.apply(a,b)}}}else h={remove:function(){var a=h.previous,c=h.next;if(!c&&!a)delete b[f];else if(a?a.next=c:b[f]=c,c)c.previous=a},id:m++,advice:a,receiveArguments:d};if(c&&!e)if("after"==f){for(;c.next&&(c=c.next););c.next=h;h.previous=c}else{if("before"==f)b[f]=h,h.next=c,c.previous=h}else b[f]=h;return h}function k(f){return function(k,
a,d,c){var e=k[a],j;if(!e||e.target!=k){k[a]=j=function(){for(var a=m,b=arguments,c=j.before;c;)b=c.advice.apply(this,b)||b,c=c.next;if(j.around)var d=j.around.advice(this,b);for(c=j.after;c&&c.id<a;){if(c.receiveArguments)var e=c.advice.apply(this,b),d=e===h?d:e;else d=c.advice.call(this,d,b);c=c.next}return d};if(e)j.around={advice:function(a,b){return e.apply(a,b)}};j.target=k}k=b(j||e,f,d,c);d=null;return k}}var h,m=0,l=k("after"),o=k("before"),f=k("around");return{before:o,around:f,after:l}})},
"dojo/_base/connect":function(){define("./kernel,../on,../topic,../aspect,./event,../mouse,./sniff,./lang,../keys".split(","),function(b,k,h,m,l,o,f,i){function n(a,c,d,e,f){e=i.hitch(d,e);if(!a||!a.addEventListener&&!a.attachEvent)return m.after(a||b.global,c,e,!0);"string"==typeof c&&"on"==c.substring(0,2)&&(c=c.substring(2));if(!a)a=b.global;if(!f)switch(c){case "keypress":c=j;break;case "mouseenter":c=o.enter;break;case "mouseleave":c=o.leave}return k(a,c,e,f)}function a(a){a.keyChar=a.charCode?
String.fromCharCode(a.charCode):"";a.charOrCode=a.keyChar||a.keyCode}f.add("events-keypress-typed",function(){var a={charCode:0};try{a=document.createEvent("KeyboardEvent"),(a.initKeyboardEvent||a.initKeyEvent).call(a,"keypress",!0,!0,null,!1,!1,!1,!1,9,3)}catch(b){}return 0==a.charCode&&!f("opera")});var d={106:42,111:47,186:59,187:43,188:44,189:45,190:46,191:47,192:96,219:91,220:92,221:93,222:39,229:113},c=f("mac")?"metaKey":"ctrlKey",e=function(b,c){var d=i.mixin({},b,c);a(d);d.preventDefault=
function(){b.preventDefault()};d.stopPropagation=function(){b.stopPropagation()};return d},j;j=f("events-keypress-typed")?function(a,b){var c=k(a,"keydown",function(a){var c=a.keyCode,g=13!=c&&32!=c&&(27!=c||!f("ie"))&&(48>c||90<c)&&(96>c||111<c)&&(186>c||192<c)&&(219>c||222<c)&&229!=c;if(g||a.ctrlKey){g=g?0:c;if(a.ctrlKey){if(3==c||13==c)return b.call(a.currentTarget,a);g=95<g&&106>g?g-48:!a.shiftKey&&65<=g&&90>=g?g+32:d[g]||g}c=e(a,{type:"keypress",faux:!0,charCode:g});b.call(a.currentTarget,c);
if(f("ie"))try{a.keyCode=c.keyCode}catch(h){}}}),h=k(a,"keypress",function(a){var c=a.charCode,a=e(a,{charCode:32<=c?c:0,faux:!0});return b.call(this,a)});return{remove:function(){c.remove();h.remove()}}}:f("opera")?function(a,b){return k(a,"keypress",function(a){var c=a.which;3==c&&(c=99);c=32>c&&!a.shiftKey?0:c;a.ctrlKey&&!a.shiftKey&&65<=c&&90>=c&&(c+=32);return b.call(this,e(a,{charCode:c}))})}:function(b,c){return k(b,"keypress",function(b){a(b);return c.call(this,b)})};var p={_keypress:j,connect:function(a,
b,c,d,e){var f=arguments,h=[],i=0;h.push("string"==typeof f[0]?null:f[i++],f[i++]);var j=f[i+1];h.push("string"==typeof j||"function"==typeof j?f[i++]:null,f[i++]);for(j=f.length;i<j;i++)h.push(f[i]);return n.apply(this,h)},disconnect:function(a){a&&a.remove()},subscribe:function(a,b,c){return h.subscribe(a,i.hitch(b,c))},publish:function(a,b){return h.publish.apply(h,[a].concat(b))},connectPublisher:function(a,b,c){var d=function(){p.publish(a,arguments)};return c?p.connect(b,c,d):p.connect(b,d)},
isCopyKey:function(a){return a[c]}};p.unsubscribe=p.disconnect;i.mixin(b,p);return p})},"dojo/errors/CancelError":function(){define(["./create"],function(b){return b("CancelError",null,null,{dojoType:"cancel"})})}}});(function(){var b=this.require;b({cache:{}});!b.async&&b(["dojo"]);b.boot&&b.apply(null,b.boot)})();